### ISSUE TITLE
Flipped scene of chat

### ISSUE THREAD

**Issue by michalraska** [badoo/Chatto#107]
Hi,

I would like to ask you for hints how to flip scene of chat to have input container placed right below navigation bar with reversed chat history (the latest message to have on top).

Do I need more than apply these steps?
- to fork repo
- to adjust methods addCollectionView and addInputViews of class ChatViewController to set proper constraints to collectionView and inputContainer
- to adjust method adjustCollectionViewInsets of class ChatViewController  to set proper collection view insets
- override ChatCollectionViewLayoutModel with verticalOffset set to 0

**Comment by diegosanchezr** [comment]
Hi @michalraska 

That's a good start. You will also need to invert the pagination logic and scroll to bottom after updates.

I've seen in other projects that they invert the UICollectionView and the cells with a 180° rotation, so you may give that idea a try also.

**Comment by michalraska** [comment]
@diegosanchezr Thank you.
