### ISSUE TITLE
Recent changes causing failed to prepare an EAGLView?

### ISSUE THREAD

**Issue by zwang** [badoo/Chatto#111]
@diegosanchezr 

Thank you and the team for all the active development and improvements.

I am trying to update my app with all the latest changes and fixes. However I got some problems related to EAGLView. I am able to re-produce the same issue in `dev` branch. The same issue does not exist on `master` branch. 

(master-eaglview branch, no issues)
https://github.com/zwang/Chatto/commit/8e9f1fd010b0eeeecf9d59ca5e6e8f4e077d5922

(mev-eaglview branch, unable to create EAGLView, same code as in master-eaglview)
https://github.com/zwang/Chatto/commit/6c6c2ccca784856ba8c27cca93f442c96fed6959

I tried to go through the changes but could not figure out which could cause the change. Do you mind give me some hints which part might cause the issue? 

Thanks. 

Screenshot about the error attached below
![screen shot 2016-04-18 at 4 35 38 pm](https://cloud.githubusercontent.com/assets/1171212/14623374/6f1a8b9a-0586-11e6-9b3c-689abb07cf54.png)

**Comment by diegosanchezr** [comment]
We've recently introduced BaseChatViewControllerView to fix https://github.com/badoo/Chatto/issues/101. Defaults UIViewControllers's view size seems to be initialized to screen bounds while BaseChatViewControllerView default size is zero and so it's your eaglLayer, which seems to cause trouble in your OpenGL code. You shouldn't rely on size of views in viewDidLoad

**Comment by zwang** [comment]
I see. Thanks a lot for the quick tip. I will look into it. Time to revisit my code. :)

**Comment by zwang** [comment]
@diegosanchezr Thanks again for the help. Just want to update you that it is because the view size is zero during viewDidLoad calls.
