### ISSUE TITLE
Make AccessoryViewRevealer optional?

### ISSUE THREAD

**Issue by zwang** [badoo/Chatto#112]
We don't want to have an accessory view in the conversation yet. Is there a way to get rid of it without changing the source code? I found it is not doable since the `accessoryViewRevealer` is internal. 

I have made some changes related to  `accessoryViewRevealer` at here: https://github.com/zwang/Chatto/commit/c6b4230459f753202298f476259d0a3dc3bb2808 for my needs. Better solution are welcome.

**Comment by diegosanchezr** [comment]
Yes, we're gonna enhance the AccessoryViewRevealer very soon. It will be possible to disable it completely and customize its behaviour a little bit.

**Comment by diegosanchezr** [comment]
Check this out: https://github.com/badoo/Chatto/pull/114

**Comment by zwang** [comment]
Nice! You guys are awesome. Thank you 👍
