### ISSUE TITLE
Wrong bounding rect for some strings when using "FS Albert Pro" font

### ISSUE THREAD

**Issue by AntonPalich** [badoo/Chatto#121]
`boundingRectWithSize(_:options:attributes:context:)` returns wrong bounding rect for string "Мруа паваЫотрПрпв." with font FS Albert Pro of size 16.00

AR: Width is equal 150
ER: Width is equal 151

A possible solution would be to use CTFramesetter to calculate string sizes because it returns correct width in this case

**Comment by AntonPalich** [comment]
Unfortunately CTFramesetter may return wrong results as well, but for height value.

Playground code (you need to add FS Albert Pro font to your playground resources):

```swift
import UIKit

func calculateSizes(string: NSAttributedString) {
    let maxSize = CGSize(width: 180, height: CGFloat.max)
    let stringSize = string.boundingRectWithSize(maxSize, options: [.UsesLineFragmentOrigin, .UsesFontLeading], context: nil).size
    print("boundingRect: \(stringSize)")

    let range = CFRangeMake(0, string.length)
    let framesetter = CTFramesetterCreateWithAttributedString(string)
    let framesetterSize = CTFramesetterSuggestFrameSizeWithConstraints(framesetter, range, nil, maxSize, nil)
    print("framesetter: \(framesetterSize)")
}

let text = "Мруа паваЫотрПрпв."

// System Font
print("System font:")
let attributes = [NSFontAttributeName: UIFont.systemFontOfSize(16)]
calculateSizes(NSAttributedString(string: text, attributes: attributes))

// FS Albert Pro font
print()
print("FS Albert Pro font:")
let url = NSBundle.mainBundle().URLForResource("FS Albert Pro", withExtension: "otf")
CTFontManagerRegisterFontsForURL(url!, CTFontManagerScope.Process, nil)
calculateSizes(NSAttributedString(string: text, attributes: [NSFontAttributeName: UIFont(name: "FSAlbertPro", size: 16)!]))

```

will produce next output:

```
System font:
boundingRect: (162.03125, 19.09375)
framesetter: (162.03125, 19.0)

FS Albert Pro font:
boundingRect: (149.872, 18.24)
framesetter: (150.672, 19.0)
```

As you can see, using CTFramesetter will solve the issue for "FS Albert Pro" font (all values are bigger than values returned from `boundingRect` function), but will introduce issue for system font. All values are rounded using `ceil` function. So, final height produced by `boundingRect` function will be 20. Difference in 1 px will be enough to miss the last line of text.

**Comment by diegosanchezr** [comment]
@AntonPalich I couldn't help myself investigating this interesting issue...

Take a look at this rendering comparison between UILabel and UITextView.
![image](https://cloud.githubusercontent.com/assets/6777207/15046807/fae3570c-12e1-11e6-87a4-257fc1924f2c.png)

UITextView's text is wider, and the distance in between "р" and "у" is slightly bigger, which leads to text kerning: https://www.objc.io/issues/5-ios7/getting-to-know-textkit/

The following seems to solve the issue, although I didn't test it thoroughly with different font faces and sizes...
 
```swift
@@ -237,7 +237,10 @@ private final class TextBubbleLayoutModel {
         return self.layoutContext.text.boundingRectWithSize(
             CGSize(width: width, height: CGFloat.max),
             options: [.UsesLineFragmentOrigin, .UsesFontLeading],
-            attributes: [NSFontAttributeName: self.layoutContext.font], context:  nil
+            attributes: [
+                NSFontAttributeName: self.layoutContext.font,
+                NSKernAttributeName: 0,
+            ], context:  nil
         ).size.bma_round()
     }
 }
```

ps: our size calculation should match UITextView.sizeThatFits(_:) after rounding. We're using boundingRectWithSize because it's way faster and UITextView can't be used in the background.

**Comment by AntonPalich** [comment]
@diegosanchezr Great! This solved the issue, i'll revert previous changes
