### ISSUE TITLE
Date heading cells

### ISSUE THREAD

**Issue by realsurfer** [badoo/Chatto#147]
Hello,

Would it be possible to easily add dates between the cells? I know that I can swype from the right to show the dates but it would be nice to have a date heading displayed i.e one per day just like many apps do such as Apple's messages or the Badoo app.

Thanks
Michael

**Comment by diegosanchezr** [comment]
You can check out ChattoApp, there's an example of just that there.

**Comment by realsurfer** [comment]
Thanks for your reply! 

I am running ChattoApp but can't see dates between cells. When do they appear? Are these decorator views?

**Comment by diegosanchezr** [comment]
Yes, in ChattoApp the time separators are inserted in ChatItemsDemoDecorator by comparing the dates of the messages - but you can deal with them directly from your dataSource if that's more convenient for you.
