### ISSUE TITLE
no shared framework schemes for any of the platforms: iOS

### ISSUE THREAD

**Issue by makoni** [badoo/Chatto#158]
There's an error when you building Chatto with Carthage:

`carthage update --platform iOS`

*** Skipped building Chatto due to the error:
Dependency "Chatto" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/badoo/Chatto/issues/new

**Comment by diegosanchezr** [comment]
Thanks for reporting - it's been broken on dev branch recently after updating pods in ChattoApp (with CocoaPods 1.0.1).

If I share frameworks inside ChattoApp then it will work (but output reports that it builds them from Chatto.xcworkspace, which is what we want, but doesn't make any sense with not being able to find them now). So I'm not sure at this point if Carthage is building the frameworks with the Pod's configuration or the one in Chatto.xcworkspace (difference is whole-module optimization for release)

I'll push the "fix" now

**Comment by diegosanchezr** [comment]
Please check again

**Comment by makoni** [comment]
Building works, thank you 👍🏼
