### ISSUE TITLE
How to display an avatar next to the message?

### ISSUE THREAD

**Issue by weyert** [badoo/Chatto#16]
How can I display an avatar next to the message, like in iMessage?

**Comment by diegosanchezr** [comment]
I'm afraid there's no support for that, so a PR adding that functionally would be greatly appreciated : )

**Comment by weyert** [comment]
I would be happy to give it a shot @diegosanchezr but where should I start? Any chance you could give some hints?

**Comment by diegosanchezr** [comment]
I'd go by adding an avatar view to BaseMessageCollectionViewCell and then I'd forward the changes up to the view models and BaseMessagePresenter. Please make sure everything you add is opt-in and doesn't require changes to existing clients (or at least changes are minimum).

**Comment by weyert** [comment]
Thanks, I will have a closer look at it. I would assume you would prefer optional's or the default settings to be so that avatar isn't being shown, correct?

**Comment by diegosanchezr** [comment]
Exactly, existing behaviour should be preserved. About "optionals" in protocols, we make them by adding default implementations in protocol extensions.

**Comment by weyert** [comment]
Thanks, I will have a look tomorrow. Happy New Year to you! Three hours left for me.

**Comment by diegosanchezr** [comment]
Same here :D. Happy new year!

**Comment by weyert** [comment]
I have made a start:
https://github.com/weyert/Chatto/commit/9bd9f9623f5734f0580f7626fe45160b1d4411d0

Tomorrow, I will think about the best approach to deal how to pass the actual avatar image. Guess in the view model itself.

**Comment by weyert** [comment]
Changed that branch a bit more so that its actually displaying an avatar image when passed. I only don't know how to change the defaults of `BaseMessageCollectionViewCellDefaultSyle`-class or how to change these preferences in the Chatto test application.

**Comment by diegosanchezr** [comment]
Well you should define a default avatar size as you did (do you really need different sizes for incoming/outgoing?). However, if there's an avatar (and the avatar image itself) should reside in the messageViewModel. Then you should take the same approach as in PhotoMessageViewModel to load the images (observable property, but no downloading of images there, cause we don't want to couple the framework with any downloading framework). Then it'd be nice to add a FakeMessageViewModel to fake loading of avatars as it's done with photo messages, so we can add a new conversation in ChattoApp showing a group chat. Also, please avoid using magic numbers for margins with the avatar and that kind of stuff. It'd be awesome if you can implement all this, thank you!

**Comment by weyert** [comment]
Oh, I had added it to the MessageModel:
https://github.com/weyert/Chatto/commit/c72a34879f18baa4aa10d8d1a1f5f0351e60ea3e

I will have a look at it again. Currently, struggling with implementing the data source protocol for my own project/app.

**Comment by weyert** [comment]
I will have a look at it again this week. Back from the holidays. So it should be better to move the avatarImage to the message view model then?

**Comment by diegosanchezr** [comment]
Yes, definitely.

**Comment by zwang** [comment]
Hi @weyert 

Thanks for doing this. Just want to put my two cents. 

It seems to me that the magic number `10` in line 381 in the new file in commit https://github.com/weyert/Chatto/commit/9bd9f9623f5734f0580f7626fe45160b1d4411d0 is meant to be `horizontalInterspacing` just like for outgoing cell case. 

And I agree with @diegosanchezr that one Avatar size is what we needed, unless you show two avatar in one cell, which should be a very rare case.

**Comment by weyert** [comment]
@zwang has implemented this feature the right away. Lots of thanks to him. :)

**Comment by zwang** [comment]
@weyert I am glad I can help. :)
