### ISSUE TITLE
migrating to swift 3

### ISSUE THREAD

**Issue by askari01** [badoo/Chatto#160]
**while migrating to swift 3**
chatViewController.swift

Static member 'weakMemory' cannot be used on instance of type ‘PointerFunctions.Options'
`let presentersByChatItem = MapTable(keyOptions: .weakMemory , valueOptions: PointerFunctions.Options())`
`let presentersByCell = MapTable(keyOptions: .weakMemory, valueOptions: .WeakMemory)`

**Comment by diegosanchezr** [comment]
This should work:

MapTable<UICollectionViewCell, AnyObject>(keyOptions: .weakMemory, valueOptions: .weakMemory)

If you're successful with the migration, could you share your branch with us? Thank you!

**Comment by diegosanchezr** [comment]
wtf, the generics are hidden in my previous comment. This is what I meant:

```Swift
MapTable<UICollectionViewCell, AnyObject>(keyOptions: .weakMemory, valueOptions: .weakMemory)
```

**Comment by indrajitsinh** [comment]
@askari01  if you're successful with the migration, can you please share it with community ? Thank you

**Comment by diegosanchezr** [comment]
I got it working with the latest beta 🎉. Check it [here](https://github.com/badoo/Chatto/tree/swift-3)!

**Comment by askari01** [comment]
@diegosanchezr this thread should be closed now

**Comment by weyert** [comment]
Should this be working with the latest build? As it's not compiling for me when using the `swift-3` branch using Carthage.

**Comment by diegosanchezr** [comment]
@weyert should be working now with beta 5

**Comment by anupamme** [comment]
I tried with beta 6 and I get compile errors: one of which is in BaseChatViewController+Presenters.swift:
 `@objc(collectionView:canPerformAction:forItemAtIndexPath:withSender:)
    public func collectionView(_ collectionView: UICollectionView, canPerformAction action: Selector, forItemAt indexPath: IndexPath, withSender sender: AnyObject?) -> Bool {
        return self.presenterForIndexPath(indexPath).canPerformMenuControllerAction(action) ?? false
    }`

And there are few other errors as well. I am using the swift-3 branch. Let me know if I am missing something out here.

**Comment by diegosanchezr** [comment]
You're not missing anything, beta 6 came out yesterday and it's not supported yet. No guarantees that I will migrate to each beta, so feel free to make a PR to this branch if you do. Cheers!

**Comment by weyert** [comment]
Thanks, Diego! I have to admit it's a pain to keep it all working with each new beta of Xcode 8. Why do they keep changing Swift 3 language between beta's :P
