### ISSUE TITLE
BaseViewController leaks in tests

### ISSUE THREAD

**Issue by AntonPalich** [badoo/Chatto#163]
Next tests fails in `dev` branch:

```
BaseChatViewControllerTests.testThat_WhenUpdatesFinish_ControllerIsNotRetained
BaseChatViewControllerTests.testThat_WhenLayoutFinishes_ControllerIsNotRetained
```

**Comment by diegosanchezr** [comment]
They pass for me and Travis: https://travis-ci.org/badoo/Chatto/builds/139774280

Any iOS version / device in particular??

**Comment by AntonPalich** [comment]
Tests fails if they are compiled for armv7 architecture (iPhone 4s/5, iPad 2/3) on iOS 9.3 (iOS 8.4 is fine). I'm looking for the problem

**Comment by AntonPalich** [comment]
Issue is in UIKit. This test fails on iPhone 4S/5, iPad 2/3 with iOS 9.3:

```swift
func testThat_ViewControllerLeaks() {
    var viewController: UIViewController? = UIViewController()
    weak var weakViewController = viewController
    viewController?.view.frame = CGRect.zero
    viewController = nil
    XCTAssertNil(weakViewController)
}
```

**Comment by AntonPalich** [comment]
Compiler inserts retain/release/autorelease differently on different architectures:

armv7:
<img width="886" alt="armv7" src="https://cloud.githubusercontent.com/assets/1708330/16356799/bbfa1e40-3adc-11e6-8f2c-7bfb084ea34e.png">

armv64
<img width="855" alt="armv64" src="https://cloud.githubusercontent.com/assets/1708330/16356809/eba5315c-3adc-11e6-9d3b-609ec826d289.png">

On armv7 additional autorelease message doesn't allow controller to be deallocated during test execution
