### ISSUE TITLE
Example code doesn't work

### ISSUE THREAD

**Issue by simonexmachina** [badoo/Chatto#17]
The example code in the README doesn't cover all the required steps to get a Chatto implementation working. I think it would be good to have a minimal implementation to help people get started, and ChattoApp (inside the Chatto repo) doesn't seem to be minimal.

I had to copy a whole lot of things from the ChattoApp in order to get the example code to work. Here's a list of some of the errors.
- `TextMessageHandler` is not defined
- `TextMessageModel.chatItemType` is not defined
- `FakeMessageSender` is not defined
- `ViewController' has no member 'baseMessageHandler'`
- `ViewController' has no member 'configureChatInputBar'`: removed
- `ViewController' has no member 'chatInputPresenter'`: removed

Solution to get it to build and run was as follows:
- Copied `FakeDataSource.swift SlidingDatasSource.swift Source/FakeMessageFactory.swift` into my project.
- Added the following to configure the `messageSender` and `dataSource` and `baseMessageHandler`:

``` swift
    var messageSender: FakeMessageSender!
    var dataSource: FakeDataSource! {
        didSet {
            self.chatDataSource = self.dataSource
        }
    }
    private var baseMessageHandler: BaseMessageHandler

    required init?(coder aDecoder: NSCoder) {
        dataSource = FakeDataSource(count: 0, pageSize: 0)
        messageSender = dataSource.messageSender
        baseMessageHandler = BaseMessageHandler(messageSender: messageSender)
        super.init(coder: aDecoder)
    }
```

**Comment by diegosanchezr** [comment]
It was never the intention to provide a ready-to-compile code in the readme, but just an overview explaining the basics on how things work. Anyway, we take your feedback on board for future updates. Thank you!

**Comment by ogezue** [comment]
A simplified example would be very appreciated. I looking at your example and have to figure out what to implement to make it work for me.

**Comment by commando24** [comment]
yeah agree with @ogezue please explain everything properly.

**Comment by NinoScript** [comment]
The example is kind of convoluted and confusing, a minimal usable example would really be great.

**Comment by Kamaldeep-Singh** [comment]
The chatto examples are so complex with multiple layers of inheritance. Thumbs down to this library.

**Comment by Daxito** [comment]
Personally, I like the example, it helped me to be up and running in no time.
