### ISSUE TITLE
Unable to find module

### ISSUE THREAD

**Issue by bangarharshit** [badoo/Chatto#185]
After doing pod install app is still unable to find module. I have used the dependency from readme project. is there something needed to be changed in info.plist?

**Comment by diegosanchezr** [comment]
It's difficult to help with such little info:
 - What exact error are you getting?
 - What version of Chatto are you trying to use? (1.0.x/dev)
 - What version of cocoapods are you using?
 - How can we reproduce the same issue? (provide an example project if possible)

Nothing is required regarding info.plist

**Comment by bangarharshit** [comment]
Sample project - https://bitbucket.org/HarshitBangar/chat-client-ios Xcode - 7.3.1(7D104)  and cocoa pod - 1.0.1 . I am able to import all the other projects like AlomaFire but some how chatto and chatto additions are not visible.

**Comment by diegosanchezr** [comment]
@bangarharshit I can't reproduce your problem - it just works fine for me. Can you push a branch after running pod install and some use of Chatto/ChattoAdditions?

If you're starting now with Chatto I highly recommend you to use "dev" branch - Chatto 2.0 is "imminent" and has some breaking API changes and a lot of bugfixes and improvements

**Comment by bangarharshit** [comment]
Chatto 2.0 can I download through pod (or anything without git). I see in your dev branch pod spec version is still 1.0

**Comment by diegosanchezr** [comment]
You can use this in your Podfile to use dev branch:
```
pod 'Chatto', :git => 'https://github.com/badoo/Chatto', :branch => 'dev'
pod 'ChattoAdditions', :git => 'https://github.com/badoo/Chatto', :branch => 'dev'
```

**Comment by bangarharshit** [comment]
Cool this is working for me. Closing the issue.
