### ISSUE TITLE
Getting error 1 when try to archive ChattoApp 

### ISSUE THREAD

**Issue by seidju** [badoo/Chatto#187]
Hi everyone!
When I try to Archieve `ChattoApp` from `prepare-release--2.0` or `dev` branch I'm getting this error:
`Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1`
I'm using XCode 7.3.1
Thanks for any help!

**Comment by diegosanchezr** [comment]
This another bug in the compiler :( - I've just filled https://bugs.swift.org/browse/SR-2223 (feel free to vote :) )

Workaround: Enable whole module optimization for ChattoAdditions

If you're using Carthage that's set already, so everything should be fine. For Cocoapods you can add a post_install phase to your `Podfile`:
```
# workaround for https://bugs.swift.org/browse/SR-2223
post_install do |installer_representation|
  installer_representation.pods_project.targets.each do |target|
    if target.name == 'ChattoAdditions'
      target.build_configurations.each do |config|
        if config.name == 'Release'
          config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
        end
      end
    end
  end
end
```

Thanks for letting us know!

**Comment by seidju** [comment]
@diegosanchezr thank you, that's it!
