### ISSUE TITLE
Question: Can I create a full width bubble?

### ISSUE THREAD

**Issue by axitkhurana** [badoo/Chatto#189]
Was wondering if I could add a full width (width equal to width of the screen) in Chatto?

I need to display a banner of information inside the chat stream.

Thanks!

**Comment by diegosanchezr** [comment]
Yes, cells get all the available width. Take a look at time separators in ChattoApp

**Comment by axitkhurana** [comment]
Thanks @diegosanchezr 

Found the following in ChattoAdditions

```
public struct BaseMessageCollectionViewCellLayoutConstants {
    let horizontalMargin: CGFloat = 11
    let horizontalInterspacing: CGFloat = 4
    let maxContainerWidthPercentageForBubbleView: CGFloat = 0.68
}
```
The best I could do using the above parameters is:

![screen shot 2016-08-02 at 1 59 14 pm](https://cloud.githubusercontent.com/assets/667376/17345146/8580a10e-58b9-11e6-9e06-f59a5c1feff4.png)

Can I get rid of the small white margin around the grey tailless bubble as well? Is that part of the bubble image?

**Comment by diegosanchezr** [comment]
Are you really sure that you want to hack a text bubble into a full-width banner? 🙈

Anyway, answering your question, the gap you see it is part of the image. If you want to continue with this hack, you can provide your own images by creating your own TextMessageCollectionViewCellStyleProtocol or reusing TextMessageCollectionViewCellDefaultStyle with your images. Playing with the insets there and BaseMessageCollectionViewCellLayoutConstants you should be able to create that abomination.

**Comment by axitkhurana** [comment]
Haha, maybe not if there's a better way, can I insert a banner in the chat stream without making it a "bubble" ? @diegosanchezr

**Comment by diegosanchezr** [comment]
Sure, that's why I mentioned time separators, it's the simplest example of a custom cell. You will need:
 - The cell: this is your banner UI
 - The model: should provide the data needed for your banner
 - The presenter: this is the guy who will configure the cell with your model
 - The presenter builder: this is the guy that Chatto will use to create your presenter

Take a look at TimeSeparatorPresenter.swift in ChattoApp.

**Comment by axitkhurana** [comment]
Oh awesome, I misunderstood, thanks I'll look into it.

**Comment by axitkhurana** [comment]
Hey @diegosanchezr, couldn't find TimeSeparatorPresenter.swift, did you mean SendingStatusPresenter.swift?

**Comment by diegosanchezr** [comment]
Oh, please grab `dev` branch. We're gonna release Chatto 2.0 from there very soon

**Comment by axitkhurana** [comment]
Makes sense now!

Unable to compile dev branch with following error:

```
invalid linkage type for global declaration
i8** @_TWPVSC14UIControlStates9Equatable5UIKit
LLVM ERROR: Broken module found, compilation aborted!
```
For the following files

```
The following build commands failed:
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
        CompileSwift normal arm64 /Users/akshit/ios-app/Pods/ChattoAdditions/ChattoAdditions/Source/Input/Photos/PhotosChatInputItem.swift
        CompileSwift normal arm64 /Users/akshit/ios-app/Pods/ChattoAdditions/ChattoAdditions/Source/Input/Text/TextChatInputItem.swift
```

Tracking in #192

Let me know if additional information would be helpful to debug this.

Thanks for the help @diegosanchezr !
