### ISSUE TITLE
Dev branch fails compilation

### ISSUE THREAD

**Issue by axitkhurana** [badoo/Chatto#192]
Getting

```
invalid linkage type for global declaration
i8** @_TWPVSC14UIControlStates9Equatable5UIKit
LLVM ERROR: Broken module found, compilation aborted!
```

For the following files

```
The following build commands failed:
        CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
        CompileSwift normal arm64 /Users/akshit/ios-app/Pods/ChattoAdditions/ChattoAdditions/Source/Input/Photos/PhotosChatInputItem.swift
        CompileSwift normal arm64 /Users/akshit/ios-app/Pods/ChattoAdditions/ChattoAdditions/Source/Input/Text/TextChatInputItem.swift
```

It's failing with my project but succeeds in ChattoApp. Not sure what more information about my project would be useful to debug the issue. Thanks!

Master branch compiles.

**Comment by diegosanchezr** [comment]
This seems related to https://github.com/badoo/Chatto/issues/187

Can you provide?

- Xcode version
- Cocoapods/Carthage version
- Swift optimization level

**Comment by axitkhurana** [comment]
* Xcode Version 7.3.1 (7D1014)
* `pod --version` :  0.39.0
* None [-Onone]

**Comment by diegosanchezr** [comment]
can't reproduce, can you share a project where this happens?

**Comment by axitkhurana** [comment]
I wish I could @diegosanchezr. 

The workaround in https://github.com/badoo/Chatto/issues/187#issuecomment-236364997 you suggested helped.
