### ISSUE TITLE
How to turn off URL support?

### ISSUE THREAD

**Issue by felixchan** [badoo/Chatto#20]

**Comment by zwang** [comment]
Check out `TextBubbleView.viewContext` `didSet` related code for example. Copy the code as below

    public var viewContext: ViewContext = .Normal {
        didSet {
            if self.viewContext == .Sizing {
                self.textView.dataDetectorTypes = .None
                self.textView.selectable = false
            } else {
                self.textView.dataDetectorTypes = .All
                self.textView.selectable = true
            }
        }
    }

These are 6 types of detections:

    public static var PhoneNumber: UIDataDetectorTypes { get } // Phone number detection
    public static var Link: UIDataDetectorTypes { get } // URL detection
    @available(iOS 4.0, *)
    public static var Address: UIDataDetectorTypes { get } // Street address detection
    @available(iOS 4.0, *)
    public static var CalendarEvent: UIDataDetectorTypes { get } // Event detection
    
    public static var None: UIDataDetectorTypes { get } // No detection at all
    public static var All: UIDataDetectorTypes { get } // All types

Not sure how to enable only detect any two, i.e. PhoneNumber and Address though.
