### ISSUE TITLE
network loaded avatar image

### ISSUE THREAD

**Issue by alibasta** [badoo/Chatto#203]
Hi,

whats the recommended way to load avatar images from the network?

I only see the following code in the demo project:

ViewModelBuilderProtocol implementation: 
```
avatarImage.value = UIImage(named: "userAvatar")
```

Thanks!

Best

Alex

**Comment by diegosanchezr** [comment]
It should be done in the view model. Look at DemoPhotoMessageViewModel.willBeShown, there you could trigger your download and set the image once it's finished. The presenter will get notified when avatarImage.value changes and reconfigure the cell.

Another approach would be to create your own PhotoMessagePresenter and access BaseMessageCollectionViewCell.avatarView directly

**Comment by realsurfer** [comment]
Hi,

Is there any way to access the avatar image view to be able to set the corner radius?

Thanks!
Michael

**Comment by zj2050** [comment]
@diegosanchezr can give a example for how to set photo image form network ? thx
