### ISSUE TITLE
How can I make main chat VC support smaller UICollectionView

### ISSUE THREAD

**Issue by pkasson** [badoo/Chatto#208]
I am adding this great project to my own and the VC that calls the ChatVC is not a nav controller, so there is no Nav bar or Nav item at the top, and the CollectionView takes up all of the screen (aside from keyboard area at bottom).

I am adding my own buttons / nav area to the top, but the CV takes up the entire screen ... have been trying to resize the CV but no go.  How can I shrink the CV so that it is between a top nav area and the bottom text area?  

Thank you !

**Comment by diegosanchezr** [comment]
You can try modifying BaseChatViewController.Constants.defaultContentInsets or embed the chat in a child view controller that only takes the area that you want

**Comment by pkasson** [comment]
Awesome ideas - thanks for the reply !
