### ISSUE TITLE
Keyboard does not auto hide after enter text

### ISSUE THREAD

**Issue by pkasson** [badoo/Chatto#209]
Looking to have keyboard auto hide when a text message is sent, but don't see how.  I tried to call the notifications setup as in base code:

-         self.notificationCenter.addObserver(self, selector: "keyboardWillShow:", name: UIKeyboardWillShowNotification, object: nil)
-         self.notificationCenter.addObserver(self, selector: "keyboardDidShow:", name: UIKeyboardDidShowNotification, object: nil)
-         self.notificationCenter.addObserver(self, selector: "keyboardWillHide:", name: UIKeyboardWillHideNotification, object: nil)
-         self.notificationCenter.addObserver(self, selector: "keyboardWillChangeFrame:", name: UIKeyboardWillChangeFrameNotification, object: nil)

but not firing ... and this may not be the best way.

How can I auto hide kbd ?

**Comment by diegosanchezr** [comment]
You can use `self.view.endEditing(true)` in your view controller when a message is going to be inserted

**Comment by pkasson** [comment]
Thanks, I will try that !
