### ISSUE TITLE
First message hidden behind NavigationBar in iOS 9.0.x

### ISSUE THREAD

**Issue by zwang** [badoo/Chatto#21]
This is not Chatto's bug, but it effects Chatto.

Only In iOS 9.0.x, the issue is if there is only a couple of messages in the view controller, and does not take the whole space, then the first 1 or 2 messages are hidden underneath the Navigation Bar. This can be reproduced by going to Empty Chat View Controller and send a message. Note, it only exist in iOS 9.0.x. All the other versions after iOS 8 are tested and behave correctly. 

I had a fix demod here: https://github.com/zwang/UICollectionViewTest. Please let me know if I can send a pull request based on that temp fix. Or if any one has a better solution, I am all ears. 

Thanks. 

![screen shot 2016-01-21 at 3 40 06 pm](https://cloud.githubusercontent.com/assets/1171212/12498154/4f0a601c-c055-11e5-8100-704dee9d826a.png)

**Comment by diegosanchezr** [comment]
Hi @zwang! Thank you so much for spotting this issue. I've applied fix in https://github.com/badoo/Chatto/pull/22. That should also fix the case for when the device is rotated

**Comment by zwang** [comment]
Cool Thanks. The fix looks much simpler than mine.
