### ISSUE TITLE
Best way to implement read/unread function

### ISSUE THREAD

**Issue by ivan-ushakov** [badoo/Chatto#212]
What is the best way to do read/unread function? As I understand we have `dequeue` method in cell presenter and this is a point when message being presented and we could consider it read. Am I right or there is another place for this logic?

**Comment by diegosanchezr** [comment]
It really depends on your logic to mark messages as read. If it is on a per message basis, then the cellWillBeShown it's the best place to do it. If it's something like only when reaching the end of the conversation then it's more simple to do in the view controller by listening to UICollectionViewDelegate callbacks.
