### ISSUE TITLE
How to make PhotoMessageView without any bubble background

### ISSUE THREAD

**Issue by Atimca** [badoo/Chatto#217]
Hello, thx for great work!
 But it's very hard to understand some stuff without big documentation.
I want to create sticker messages and I think, that the easiest way for it  it's make custom config for PhotoMessageView. I want to remove all bubble experience for PhotoMessageView and set custom size. How can I do this things?

**Comment by diegosanchezr** [comment]
Hi,

Take a look at PhotoBubbleViewStyleProtocol
```Swift
public protocol PhotoBubbleViewStyleProtocol {
    func maskingImage(viewModel viewModel: PhotoMessageViewModelProtocol) -> UIImage
    func borderImage(viewModel viewModel: PhotoMessageViewModelProtocol) -> UIImage?
    func placeholderBackgroundImage(viewModel viewModel: PhotoMessageViewModelProtocol) -> UIImage
    func placeholderIconImage(viewModel viewModel: PhotoMessageViewModelProtocol) -> (icon: UIImage?, tintColor: UIColor?)
    func tailWidth(viewModel viewModel: PhotoMessageViewModelProtocol) -> CGFloat
    func bubbleSize(viewModel viewModel: PhotoMessageViewModelProtocol) -> CGSize
    func progressIndicatorColor(viewModel viewModel: PhotoMessageViewModelProtocol) -> UIColor
    func overlayColor(viewModel viewModel: PhotoMessageViewModelProtocol) -> UIColor?
}
```

Some tips:
```Swift
public func tailWidth(viewModel viewModel: PhotoMessageViewModelProtocol) -> CGFloat {
    return 0
}

public func borderImage(viewModel viewModel: PhotoMessageViewModelProtocol) -> UIImage? {
    return nil
}

public func maskingImage(viewModel viewModel: PhotoMessageViewModelProtocol) -> UIImage {
    return UIImage.bma_imageWithColor(.blackColor(), size: CGSize(width: 1, height: 1))
}
```

However, you may have some issues with the transferring status. We use a white circular upload progress on top of a darkening overlay that will look bad on top of your borderless sticker. If you disable this overlay color (overlayColor(viewModel:) -> UIColor? - just return nil) then the border will be fine, but the progress may not be visible depending on the color of the sticker. One solution to this would be to tint the sticker itself depending on the status of the message.

Reusing UI is complicated, there are so many details and product requirements that can change over time than trying to make a universal, super extensible component just doesn't make sense. It may be better to create your own StickerMessageCollectionViewCell

**Comment by Atimca** [comment]
Hello, thx I will try to create StickerMessageCollectionViewCell.
