### ISSUE TITLE
Is ChattoAdditions Swift 2.3 compatible?

### ISSUE THREAD

**Issue by irace** [badoo/Chatto#219]
Seeing the following error message when trying to compile for Swift 2.3:

<img width="750" alt="screen shot 2016-09-14 at 11 05 09 am" src="https://cloud.githubusercontent.com/assets/399560/18523920/261b9a10-7a6b-11e6-88f8-5b2d38920710.png">

**Comment by VahanMargaryan** [comment]
replace `NSObject .copy(_:)` with `UIResponderStandardEditActions.copy(_:)`

```
    public override func canPerformMenuControllerAction(action: Selector) -> Bool {
        return action == #selector(UIResponderStandardEditActions.copy(_:))
    }

    public override func performMenuControllerAction(action: Selector) {
        if action == #selector(UIResponderStandardEditActions.copy(_:)) {
            UIPasteboard.generalPasteboard().string = self.messageViewModel.text
        } else {
            assert(false, "Unexpected action")
        }
    }
```

**Comment by irace** [comment]
Hi, yes thanks I was able to figure this out. But it’d be great if an official version of Chatto with this fix integrated into it was submitted to CocoaPods. Thank you!

**Comment by diegosanchezr** [comment]
Chatto 2.1.0 is Xcode 8 - Swift 2.3 compatible

**Comment by irace** [comment]
@diegosanchezr This does not seem to be the case: https://github.com/badoo/Chatto/blob/master/ChattoAdditions/Source/Chat%20Items/TextMessages/TextMessagePresenter.swift#L113
