### ISSUE TITLE
Migration to 3.0

### ISSUE THREAD

**Issue by ogezue** [badoo/Chatto#226]
I used your app with Swift 2.2 and now updated to Swift 3.0 with your updated lib. Thanks for updating so fast!

Unfortunately there are 40 non trivial build errors in my app. Do you provide some info what has changed?

**Comment by diegosanchezr** [comment]
It's better if you provide some specific examples. We didn't make any changes to the API different than the migrator, apart from ChatDataSourceProtocol.adjustNumberOfMessages(....) where we wrapped the completion closure parameter within a tuple to keep the argument label at call site.

**Comment by ogezue** [comment]
Ic could migrate the app with the help of your example. Wasn't to difficult :)
