### ISSUE TITLE
New iOS10 UICollectionView capabilities for better performance

### ISSUE THREAD

**Issue by seidju** [badoo/Chatto#228]
Hello! So, in iOS 10 Apple presented new `UICollectionView` cell lifecycle with `willDisplayCell` method and also new `prefetchDataSource`. Would it help to improve performance by implementing this new approach in existing Chatto code?
Thanks!

**Comment by diegosanchezr** [comment]
Hi @seidju, we sure can do something with `prefetchDataSource`.

`willDisplayCell` has been always there and it's already being forwarded to the presenters.

**Comment by pkasson** [comment]
Does this allow for displaying chat history faster as well ?
