### ISSUE TITLE
Edit Text bubble with image as background

### ISSUE THREAD

**Issue by dromerobarria** [badoo/Chatto#23]
First, thanks for the nice job , your framework has been really helpfully.

I would like to know is there any way to change or modify the text bubbles, thing like background for a image , or if i want to add a label (to show something else) .

**Comment by diegosanchezr** [comment]
Hi @dromerobarria,

Glad to hear you find the framework useful :) For customization of bubbles you can take a look at textCellStyle/photoCellStyle and baseMessageStyle in TextMessagePresenterBuilder/PhotoMessagePresenterBuilder; those should allow you to change the shape and insets of text bubbles, failed icon, placeholder for images (see PhotoBubbleViewStyleProtocol) and others. For more specific changes as the label you mention you will have to modify the bubbles yourself.
