### ISSUE TITLE
Reimplement textMessage info.

### ISSUE THREAD

**Issue by Atimca** [badoo/Chatto#236]
Hello! Thx for ur work, it's really great! But I have a question.

I'm creating some app based on chatto, with bubble interaction. When I tapped on bubble I change some info on it, but I scroll or add new message it's refresh all new bubble info to previous, of cause. 

My question is: where can I find and change textMessage info, for saving my new message info?

**Comment by diegosanchezr** [comment]
Chatto doesn't come with any backend. It's your responsibility to manage and persist your chat messages if you need so. If you need to modify your messages because of some user interaction, then you need to hook access to your data layer from the message presenters or interaction handlers.
