### ISSUE TITLE
Not possible to support custom UIMenuItem

### ISSUE THREAD

**Issue by RustyKnight** [badoo/Chatto#237]
Xcode 8.1b2/Swift 3.0.1

I've been playing around with this over the last couple of days, and come to the conclusion that it's simply impossible to support custom `UIMenuItem`'s.

From my understanding of the problem, the `UICollectionViewCell` MUST implement the selector function to be called, otherwise, no matter what is done, there doesn't seem to be away to get the custom `UIMenuItem` to appear.

This can't be done because the generic support the `BaseMessageCollectionViewCell` provides as Swift keeps complaining that: 

> Argument of '#selector' refers to instance method 'banana' that is not exposed to Objective-C

(and the fact that the `#selector` syntax requires the generics to be solved in a meaningful manner) and if you add `@objc` to the function (via an extension) it complains:

> @objc is not supported within extensions of generic classes

And the fact that `func collectionView(_ collectionView: UICollectionView, performAction action: Selector, forItemAt indexPath: IndexPath, withSender sender: Any?)` doesn't get called as part of this process, just makes it even more difficult to generate a generic solution

**Comment by wiruzx** [comment]
You should be able to implement this selector in your BubbleView class.
