### ISSUE TITLE
Release in CocoaPods does not compile in XCode 8.1 / Swift 3.0.1

### ISSUE THREAD

**Issue by Aggouri** [badoo/Chatto#244]
Release 3.0.0 used for the latest Pods release does not compile under XCode 8.1. The master branch is OK.

In `KeyboardTrackingView`

```
private override var intrinsicContentSize: CGSize {
    // body
}
```

and

```
private override func observeValue(forKeyPath keyPath: String?, of object: Any?, change: [NSKeyValueChangeKey : Any]?, context: UnsafeMutableRawPointer?) {
    // body
}
```

produce the following errors:

```
[...]/Chatto/Chatto/Source/ChatController/Collaborators/KeyboardTracker.swift:204:26: 
Overriding var must be as accessible as its enclosing type

[...]/Chatto/Chatto/Source/ChatController/Collaborators/KeyboardTracker.swift:222:27: 
Overriding instance method must be as accessible as its enclosing type
```

The master branch does not exhibit this issue because the accessibility of the above var and method is different (i.e. `private` removed).

**Comment by alexsanderkhitev** [comment]
Hello @Aggouri  please look at [this conversation](https://github.com/badoo/Chatto/pull/243)

**Comment by Aggouri** [comment]
@alexsanderkhitev Thanks. I had not seen it was already spotted. 

@diegosanchezr Should I close this issue or do you want to wait for the release?

**Comment by diegosanchezr** [comment]
Hi @Aggouri, let's keep this open until the issue is fixed for better visibility. Thank you!
