### ISSUE TITLE
How can I get the frame of the specific bubble? 

### ISSUE THREAD

**Issue by alexanderkhitev** [badoo/Chatto#246]
Hello! I use class ChatPhotoMessageHandler: BaseMessageInteractionHandlerProtocol {}. How can I get the frame of the specific bubble in the userDidTapOnBubble func?

**Comment by diegosanchezr** [comment]
Hi @alexsanderkhitev, sorry for the late response.

This is not possible now. We can probably add the corresponding view parameters to BaseMessageInteractionHandlerProtocol as we did with userDidTapOnFailIcon.

Alternatively, you can override `BaseMessagePresenter.onCellBubbleTapped()` and hook your custom callbacks there

**Comment by alexsanderkhitev** [comment]
Hi @diegosanchezr. Nothing wrong. Thanks for your response!
