### ISSUE TITLE
How to Scroll To Bottom when simply clicking on the Chat Input View

### ISSUE THREAD

**Issue by rslim087g** [badoo/Chatto#251]

**Comment by rslim087g** [comment]
Hello
Is there a scroll to bottom feature every time the user taps on the chat Input bar. If not, what are ways to go about adding it.
Thank you.

**Comment by diegosanchezr** [comment]
Hi @rslim087g,

You can become delegate of ChatInputBar and perform scrollToBottom in inputBarDidBeginEditing.

**Comment by dskibin** [comment]
Hi rslim087g

trying to solve same issue that you had. I have following code:
`extension ChattoViewController: ChatInputBarDelegate{
    func inputBarShouldBeginTextEditing(_ inputBar: ChatInputBar) -> Bool{
        return true
    }
    
    func inputBarDidBeginEditing(_ inputBar: ChatInputBar){
        self.scrollToBottom(animated: false)
        
    }
.....
`
inputBarDidBeginEditing function executing when i tab on text input but chat not actually scrolling. How did you fixed that?
