### ISSUE TITLE
chatItems as a BTree or MutableOrderedDictionary

### ISSUE THREAD

**Issue by mbalex99** [badoo/Chatto#252]
In the ChatDataSourceProtocol 

```swift
public protocol ChatDataSourceProtocol: class {
    var hasMoreNext: Bool { get }
    var hasMorePrevious: Bool { get }
    var chatItems: [ChatItemProtocol] { get }
    weak var delegate: ChatDataSourceDelegateProtocol? { get set }

    func loadNext() // Should trigger chatDataSourceDidUpdate with UpdateType.Pagination
    func loadPrevious() // Should trigger chatDataSourceDidUpdate with UpdateType.Pagination
    func adjustNumberOfMessages(preferredMaxCount: Int?, focusPosition: Double, completion:((didAdjust: Bool)) -> Void) // If you want, implement message count contention for performance, otherwise just call completion(false)
}
```

We have `chatItems` in which each element is a `UniqueIdentifiable`. Maybe we should have this as a `BTree.Map<T>` or some sort of `MutableOrderedDictionary<T>`?

What do you guys think? This is a great library that might help: https://github.com/lorentey/BTree

**Comment by diegosanchezr** [comment]
What would be the benefit? Chatto already uses dictionaries to quickly calculate changes and access items - there's even public api of this representation: BaseChatViewController.chatItemCompanionCollection; but I don't see the benefit or making people's data sources more complicated.

**Comment by mbalex99** [comment]
Usually we don't mutate the BaseChatViewController though. We are to update from the dataSource.

For example if I wanted to iterate over the chatItems to find by it's `uId`, I'd have to iterate over the array. Sometimes I might want to remove messages by it's id.

**Comment by diegosanchezr** [comment]
> Usually we don't mutate the BaseChatViewController though. We are to update from the dataSource.

BaseChatViewController is immutable by design for obvious reasons. 

> For example if I wanted to iterate over the chatItems to find by it's uId, I'd have to iterate over the array. Sometimes I might want to remove messages by it's id.

You're still free to use whatever data structure you want in your data source, but I don't think we should require anything more complicated than an array, just because Chatto doesn't need it. If anything, we should relax the requirement from `Array` to `Sequence` (so if you are actually using a BTree you don't have to pay the conversion to Array) - but that would require an associated type in `ChatDataSourceProtocol` and a generic BaseChatViewController

**Comment by mbalex99** [comment]
That sounds like a good fix, generics are great for customization. The Sequence type should certainly help.

**Comment by diegosanchezr** [comment]
We're talking about a micro-optimization here. Associated types and generics also make the code more difficult to use and understand - I don't think they're the right thing to use in this case.
