### ISSUE TITLE
Status of "Typing"

### ISSUE THREAD

**Issue by lkaihua** [badoo/Chatto#257]
Hi, here is a quick question, does Chatto support showing "typing" status for incoming messages?
The background is that the server side supports keep-alive connections, so I am thinking about showing a "typing" or "..." label below the recent message.

Thanks!

**Comment by diegosanchezr** [comment]
ChattoAdditions only comes with text and photo messages, but it should be very easy to add your own typing cell.

**Comment by yarodevuci** [comment]
Any examples on how to add typing cell?

**Comment by diegosanchezr** [comment]
This may help: https://github.com/badoo/Chatto/wiki/Tutorial_Add_Custom_Cell

**Comment by jamiya** [comment]
Hello can you give complete example? Thank you.
