### ISSUE TITLE
How to change TextBubble Background Color ?

### ISSUE THREAD

**Issue by Ignasihoo** [badoo/Chatto#258]

**Comment by diegosanchezr** [comment]
Hi @Ignasihoo,

You have `TextBubbleViewStyleProtocol` and  `BaseMessageCollectionViewCellStyleProtocol` for this purpose:

```
public protocol TextBubbleViewStyleProtocol {
    func bubbleImage(viewModel: TextMessageViewModelProtocol, isSelected: Bool) -> UIImage
    func bubbleImageBorder(viewModel: TextMessageViewModelProtocol, isSelected: Bool) -> UIImage?
    func textFont(viewModel: TextMessageViewModelProtocol, isSelected: Bool) -> UIFont
    func textColor(viewModel: TextMessageViewModelProtocol, isSelected: Bool) -> UIColor
    func textInsets(viewModel: TextMessageViewModelProtocol, isSelected: Bool) -> UIEdgeInsets
}
```

```
public protocol BaseMessageCollectionViewCellStyleProtocol {
    func avatarSize(viewModel: MessageViewModelProtocol) -> CGSize // .zero => no avatar
    func avatarVerticalAlignment(viewModel: MessageViewModelProtocol) -> VerticalAlignment
    var failedIcon: UIImage { get }
    var failedIconHighlighted: UIImage { get }
    func attributedStringForDate(_ date: String) -> NSAttributedString
    func layoutConstants(viewModel: MessageViewModelProtocol) -> BaseMessageCollectionViewCellLayoutConstants
}
```

**Comment by Ignasihoo** [comment]
Hello!

Thanks for answer! But how to change bubble background color?

**Comment by popei69** [comment]
I had the same issue, the key is to set the custom color in `baseStyle` to your TextMessageCollectionViewCellDefaultStyle.

Something like that
`let chatColor = BaseMessageCollectionViewCellDefaultStyle.Colors(
    incoming: UIColor.white, // white background for incoming
    outgoing: UIColor.black // black background for outgoing
)

// used for base message background + text background
let baseMessageStyle = BaseMessageCollectionViewCellAvatarStyle(colors: chatColor)

let textStyle = TextMessageCollectionViewCellDefaultStyle.TextStyle(
    font: UIFont.systemFont(ofSize: 13),
    incomingColor: UIColor.black, // black text for incoming
    outgoingColor: UIColor.white, // white text for outgoing
    incomingInsets: UIEdgeInsets(top: 10, left: 19, bottom: 10, right: 15),
    outgoingInsets: UIEdgeInsets(top: 10, left: 15, bottom: 10, right: 19)
)

let textCellStyle: TextMessageCollectionViewCellDefaultStyle = TextMessageCollectionViewCellDefaultStyle(
    textStyle: textStyle,
    baseStyle: baseMessageStyle) // without baseStyle, you won't have the right background

let textMessagePresenter = TextMessagePresenterBuilder(
    viewModelBuilder: DemoTextMessageViewModelBuilder(),
    interactionHandler: DemoTextMessageHandler(baseHandler: self.viewModel.baseMessageHandler)
)
textMessagePresenter.baseMessageStyle = baseMessageStyle
textMessagePresenter.textCellStyle = textCellStyle
`
Hope it will avoid other people struggling with that.
