### ISSUE TITLE
Ability to add custom cells

### ISSUE THREAD

**Issue by ogezue** [badoo/Chatto#26]
Hi, I would like to have a custom cell with 3 buttons inside. Will Chatto support this?

**Comment by diegosanchezr** [comment]
Yes, take a look to the example ChatoApp, createPresenterBuilders function. You need to inject the presenter for your new cell there.

**Comment by ogezue** [comment]
great!

**Comment by ogezue** [comment]
I tried to copy TextCell and use this for my planned AppointmentCell: This cell is mainly a TextCell should contain 3 buttons to accept an appointment or not.

I stuck with this copy of TextMessageCollectionViewCell:

```
import UIKit
import Chatto
import ChattoAdditions

public typealias AppointmentMessageCollectionViewCellStyleProtocol = AppointmentBubbleViewStyleProtocol

public final class AppointmentMessageCollectionViewCell: BaseMessageCollectionViewCell<AppointmentBubbleView> {
    
    public static func sizingCell() -> AppointmentMessageCollectionViewCell {
        let cell = AppointmentMessageCollectionViewCell(frame: CGRectZero)
        cell.viewContext = .Sizing
        return cell
    }
    
    override init(frame: CGRect) {
        super.init(frame: frame)
    }
    
    // MARK: Subclassing (view creation)
    
    override func createBubbleView() -> AppointmentBubbleView {
        return AppointmentBubbleView()
    }
    
    public override func performBatchUpdates(updateClosure: () -> Void, animated: Bool, completion: (() -> Void)?) {
        super.performBatchUpdates({ () -> Void in
            self.bubbleView.performBatchUpdates(updateClosure, animated: false, completion: nil)
            }, animated: animated, completion: completion)
    }
    
    // MARK: Property forwarding
    
    override public var viewContext: ViewContext {
        didSet {
            self.bubbleView.viewContext = self.viewContext
        }
    }
    
    public var appointmentMessageViewModel: AppointmentMessageViewModelProtocol! {
        didSet {
            self.messageViewModel = self.appointmentMessageViewModel
            self.bubbleView.appointmentMessageViewModel = self.appointmentMessageViewModel
        }
    }
    
    public var appointmentMessageStyle: AppointmentMessageCollectionViewCellStyleProtocol! {
        didSet {
            self.bubbleView.style = self.appointmentMessageStyle
        }
    }
    
    override public var selected: Bool {
        didSet {
            self.bubbleView.selected = self.selected
        }
    }
    
    public var layoutCache: NSCache! {
        didSet {
            self.bubbleView.layoutCache = self.layoutCache
        }
    }
}

```

I'm getting this errors:

- AppointmentMessageCollectionViewCell.swift:18:20: Cannot invoke initializer for type 'AppointmentMessageCollectionViewCell' with an argument list of type '(frame: CGRect)'

- AppointmentMessageCollectionViewCell.swift:23:14: Initializer does not override a designated initializer from its superclass

- AppointmentMessageCollectionViewCell.swift:29:19: Method does not override any method from its superclass

- AppointmentMessageCollectionViewCell.swift:49:13: Value of type 'AppointmentMessageCollectionViewCell' has no member 'messageViewModel'


Is it really possible to add own Cells?

**Comment by diegosanchezr** [comment]
You can create your own cells from scratch. Inheriting from BaseMessageCollectionViewCell is missing `public` access level for init(frame:) and createBubbleView() so they can't be inherited outside ChattoAdditions module. You can make a PR to fix that ; )

**Comment by ogezue** [comment]
Thanks for your fast response! Are you aware of others that already have implemented own cell types?

**Comment by diegosanchezr** [comment]
ChattoApp itself does this. It has SendingStatusCollectionViewCell/SendingStatusPresenter. Unfortunately, reusing BaseMessageCollectionViewCell requires those access level changes.

**Comment by ogezue** [comment]
So I can create my AppointmentMessageModel as a copy of TextMessageModel and then create my Presenter and CollectionViewCell as a copy of SendingStatusPresenter and SendingStatusCollectionViewCell?

**Comment by diegosanchezr** [comment]
You sure need a new presenter for your cell. How you model your message I have no idea what's the best option as I don't know the details nor the exact UI you plan to write. If you want to allow timestamp revealing then you probably want to reuse BaseMessageCollectionViewCell. If that's the case then you'll need to add `public` to init(frame:) and createBubbleView(). That should fix your compiler complains.

**Comment by ogezue** [comment]
I just need a cell like this: Location and time will be inserted from a formula. So the text is alway identically. Perhaps you have an idea for this.

|––––––––––––––––––––––––––––––––––––|
|...Shall we meet at 1:30pm at the bar?...|    
| ...............................................................|                                                                 
|.......Accept......My Calendar....Decline....|     
|––––––––––––––––––––––––––––––––––––|

**Comment by diegosanchezr** [comment]
You're gonna need your own BubbleView with the text and the buttons. Then it's up to you if you want to embbed it in a BaseMessageCollectionViewCell (it gives you failed icon and timestamp) or your own UICollectionViewCell. For the model you can extend TextMessageModelProtocol / TextMessageModel

**Comment by ogezue** [comment]
Thanks - this works really great and is simpler as I thought. All I needed was 

- AppointmentPresenter: ChatItemPresenterProtocol

- AppointmentCollectionViewCell: UICollectionViewCell

- AppointmentCollectionViewCell.xib

- AppointmentModel: AppointmentModelProtocol

- AppointmentModelProtocol: TextMessageModelProtocol

**Comment by seamusapple** [comment]
@ogezue 
Hi, ogezue.
Do you have a demo to show how to add buttons in your custom cell and in which file to handle the touchUpInside event?
I have the similar requirement.
Thanks very much.
