### ISSUE TITLE
Creating custom ChatInputBar

### ISSUE THREAD

**Issue by SvRoman** [badoo/Chatto#269]
Hi!
I'm trying to make custom ChatInputBar (message text field must be on one row with "Send button"). But I can't ovveride any of methods, even nibName(). Is there some way to create custom bar?

Thanks.

**Comment by kylebrowning** [comment]
@azimin Any chance this will be answered?

**Comment by AntonPalich** [comment]
@kylebrowning You can override `BaseChatViewController. createChatInputView` function and return your own input bar.
