### ISSUE TITLE
infinite loop in performBatchUpdates 

### ISSUE THREAD

**Issue by vlmax74** [badoo/Chatto#270]
Hi, i'm using Chatto in my App but after a couple of enter background and enter foreground events, the cpu goes to 100% updating on performBatchUpdates call and never ends.
It seems the main problem is layoutSubviews method in BaseMessageCollectionViewCell as you can see in the screenshot.

![schermata 2016-12-19 alle 17 14 37](https://cloud.githubusercontent.com/assets/24655505/21319727/adfd5204-c60e-11e6-85b8-3427e7b97ade.png)

I'm using a modified version of TextBubbleView for using attributed string instead of simple String. 
When the app goes to foreground, the app make a request to a server and pushes the response in the chat. When resuming the app I can push the response in the chat adapter, but when Chatto is refreshing the layout, the cpu goes to 100% and there's no way to end the update of cells.

Max

**Comment by diegosanchezr** [comment]
Can you provide a project to reproduce the issue?

**Comment by vlmax74** [comment]
Starting from the Chat demo app, i've modified some classes to use custom servers...
The login is fake, you can just push the login button.

You can find the project at https://github.com/vlmax74/demo

**Comment by diegosanchezr** [comment]
@vlmax74, making TextBubbleView.canCalculateSizeInBackground return false fixes the issue for me.

Seems that your changes are not compatible with sizing in a background thread. Take a look here: http://stackoverflow.com/questions/21559011/nsattributedstring-from-html-in-the-background-thread

**Comment by vlmax74** [comment]
Thank you! that solved the problem.
Actually if I make my app going to background and resuming it 4 or 5 times, it hangs when sending a message. I can see the response from the server is correctly processed, but it seems that application hangs inserting the response or - maybe - updating the message sending status. I suppose there's something wrong with the sender.messageChanged in FakeDataSource.
The error seems to be "[__NSCFDictionary zIndex]: unrecognized selector sent to class"..
