### ISSUE TITLE
what is the function of viewContext in MessageCollectionViewCell and BubbleView

### ISSUE THREAD

**Issue by jk2K** [badoo/Chatto#273]
I studied the code for a long time, but I cannot understand the meaning of `viewContext`

`sizingCell()` will set `cell.viewContext` to `.sizing`
```swift
public final class PhotoMessageCollectionViewCell: BaseMessageCollectionViewCell<PhotoBubbleView> {
    ...

    static func sizingCell() -> PhotoMessageCollectionViewCell {
        let cell = PhotoMessageCollectionViewCell(frame: CGRect.zero)
        cell.viewContext = .sizing
        return cell
    }

    public override func createBubbleView() -> PhotoBubbleView {
        return PhotoBubbleView()
    }

    override public var viewContext: ViewContext {
        didSet {
            self.bubbleView.viewContext = self.viewContext
        }
    }

    ...
}
```

But I did not find the place to update PhotoBubbleView viewContext to `.normal`

 I see `updateViews()` in [PhotoBubbleView](https://github.com/badoo/Chatto/blob/master/ChattoAdditions/Source/Chat%20Items/PhotoMessages/Views/PhotoBubbleView.swift#L122)

when the value of viewContext become `.normal`?

```swift
open func updateViews() {
	if self.viewContext == .sizing { return }
	if isUpdating { return }
	guard let _ = self.photoMessageViewModel, let _ = self.photoMessageStyle else { return }

	self.updateProgressIndicator()
	self.updateImages()
	self.setNeedsLayout()
}
```

I'm confused, any help is greatly appreciated, thanks

**Comment by diegosanchezr** [comment]
There's an off-screen sizing cell in the presenters with to aid in height calculation. With an autolayout approach you use this sizing cell and systemLayoutSizeFitting(_:)

In Chatto, we have support for calculation of layout in a background thread, but UIKit is not thread safe, so we guard against modifying the view in the background with this .sizing flag. All visible cells should have viewContext == .normal

Moving forward I'd like to remove the need for the sizing cell as it's easy to forget about this. But for now, this is what we have.
