### ISSUE TITLE
how to add a loading indicator on top of the collection view to paginate messages.

### ISSUE THREAD

**Issue by jadslim313** [badoo/Chatto#279]
I attached a picture of what I'm trying to implement. Would It have to be a custom cell on top of the collection view or a UIView? Custom cells seems like the better option but I'm not quite sure how to implement that. Any guide would be very helpful

![15748403_1235833679830993_1540047740_o](https://cloud.githubusercontent.com/assets/12466304/21515568/001d97ce-cc9f-11e6-9c81-a3423a99429d.jpg)

**Comment by diegosanchezr** [comment]
I'd go with a custom cell. Have a look here: https://github.com/badoo/Chatto/wiki/Tutorial_Add_Custom_Cell

**Comment by jadslim313** [comment]
Would I be able to access the update type in the decorator? Since I would only want the loader to show if the updateType is of type pagination.

**Comment by rslim087g** [comment]
Worked like a charm
