### ISSUE TITLE
attempting to change insets in viewdidlayoutsubviews stops scrolling to bottom

### ISSUE THREAD

**Issue by jadslim313** [badoo/Chatto#281]
I tried to replicate your code in issue #51 , to add a view over the collection view.
Everything worked fine, until I had to add these two lines of code

```
override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()
    self.collectionView.contentInset.top = 0
    self.collectionView.scrollIndicatorInsets.top = 0
}
```

the problem that occured when I added the code above, is that the view stopped scrolling to bottom.

if i put scroll to bottom anywhere else the animation is ugly, why is the code above stopping the scroll to bottom from viewdidtransition, and is there any way to fix it?

**Comment by brunokoga** [comment]
I've seen this issue. Instead of overriding `viewDidLayoutSubviews()` (to reverse what the `BaseChatViewController` is doing) I fixed by doing this on `viewDidLoad`:
```
constants.defaultContentInsets = UIEdgeInsets(top: 0, left: 0, bottom: 10, right: 0)
```

**Comment by jadslim313** [comment]
thanks buddy, worked like a charm
