### ISSUE TITLE
how to disable the send button?

### ISSUE THREAD

**Issue by rslim087g** [badoo/Chatto#289]
chatInputView.sendButton.isEnabled = false
the error given is that the send button is inaccessible due to internal protection level. Is there a workaround for this. A certain situation requires me that i disable it.

**Comment by diegosanchezr** [comment]
Hi @rslim087g, there's a shouldEnableSendButton closure that you can override with your custom logic

**Comment by rslim087g** [comment]
Thank you. It worked !
