### ISSUE TITLE
Trying to use this library for the first time - Swift 3

### ISSUE THREAD

**Issue by 7Zup** [badoo/Chatto#291]
Hello, I'm having issues using chatto library.
I've follow the tutorial by copy/pasting the code given, but that doesn't compile, I have a bunch of unresolved identifier with the "demo" thing.
Is there anyway of having a test project to see how I have to implement the library ?
Thanks

**Comment by diegosanchezr** [comment]
Hi, 

The recommended integration is via cocoapods or carthage, what code are you trying to copy/paste?

**Comment by 7Zup** [comment]
I'm using cocoapods and following the tutorial found on the wiki https://github.com/badoo/Chatto/wiki/Tutorial_Setup_BaseChatViewController

**Comment by diegosanchezr** [comment]
Yeah, we should add there that those Demo* classes are not part of the frameworks. You should use your own presenters for your app. Take a look at ChattoApp example, you can find those classes there.

**Comment by 7Zup** [comment]
But, is it possible to have an exemple demo that I can download ??

**Comment by diegosanchezr** [comment]
Sure, just clone the repo and open ./ChattoApp/ChattoApp.xcworkspace

**Comment by 7Zup** [comment]
Great, I used it at that works :)
That's what I was looking for, thanks !!
That's me but, I think that you could put one or two lines for beginners like me to redirect people to this code so they don't get stuck and use another library.

Thanks anyway, I'm closing this one
