### ISSUE TITLE
Couldn't get Chatto through Carthage

### ISSUE THREAD

**Issue by Nubaslon** [badoo/Chatto#293]
Hi! When i try to get/update Carthage, i get an error - 

`*** Building scheme "Chatto" in Chatto.xcworkspace
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/blablalba/Documents/Bla/Carthage/Checkouts/Chatto/Chatto.xcworkspace -scheme Chatto -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)`

**Comment by diegosanchezr** [comment]
I just tried latest release and master branch and works for me, I'm using Carthage 0.18.1. What is your environment and what does your Cartfile look like?

**Comment by Nubaslon** [comment]
Thanks, I fix it!
