### ISSUE TITLE
Set avatar UUImage

### ISSUE THREAD

**Issue by 7Zup** [badoo/Chatto#294]
Hello,
Since that's a chat and we have the avatar icon, I'd like to change it to display the avatar of the people who are talking.
I have found where I can modify the line to have another UUImage everywhere (in "DemoTextMessageViewModel"), but I cannot put my hand on a function that allows me to do that.

I'm looking for something in the factory where you could specify some sort of UUImage for each message, is that possible?

Thanks in advance,
7Zup

**Comment by diegosanchezr** [comment]
avatarImage is an Observable<UIImage?> property in MessageViewModel. You just need to set this property and it will propagate to the cell via some presenter.
