### ISSUE TITLE
Get message text from chatItems

### ISSUE THREAD

**Issue by ji3g4m6zo6** [badoo/Chatto#295]
Should I to get the message text from chatDataSource.chatItems ?

Thanks a lot.

**Comment by diegosanchezr** [comment]
That depends on what you're trying to do. In general, you're responsible of the data source and your messages data, so you're free to access your messages in any way you want.

That said, you can access your message data at different levels
1. Your data source as I said. That's up to you what abstractions of API you build
2. At the view controller level. Here you can use chatItems as you said and index by uid
3. At the presenter level. Each presenter is built up from a chat message, so you can keep a reference to it.

**Comment by ji3g4m6zo6** [comment]
@diegosanchezr Thanks.
