### ISSUE TITLE
Release new version for Xcode8.3/Swift 3.1 compatibility.

### ISSUE THREAD

**Issue by ShaneQi** [badoo/Chatto#305]
I updated Xcode to 8.3. And there are a couple of errors because of Swift 3.1 changes.

I noticed that you've already did the compatibility update on master branch, when do you plan to release a new version (tag) for Swift 3.1?

**Comment by ogezue** [comment]
+1

**Comment by diegosanchezr** [comment]
Hey guys,

I'm sorry to let you know that I'm not actively maintaining this project any more 😥, but my ex-colleagues at Badoo will take good care of it ☺️

Regarding the removal of the warning, be aware of https://github.com/badoo/Chatto/issues/247

**Comment by think-dev** [comment]
For people using Carthage: you must use `github "badoo/Chatto" "master"` to override the error for Swift 3.1

**Comment by mbalex99** [comment]
When do you think we can cut a release? I have a podspec that has a dependency on Chatto and Cocoapods only allows for specs pushed to trunk. It doesn't allow a reference to a github branch.

**Comment by leedsalex** [comment]
@think-dev You should be able to specify the master branch or a specific commit within your Podfile. https://guides.cocoapods.org/using/the-podfile.html#from-a-podspec-in-the-root-of-a-library-repo

**Comment by think-dev** [comment]
Hi @leedsalex I'm not using CocoaPods but Carthage and it's solved using the solution I've posted above. Anyway thank you!

**Comment by leedsalex** [comment]
@think-dev I meant to mention @mbalex99, sorry about that.

**Comment by mbalex99** [comment]
@leedsalex I don't think you can specify a branch or git as in the podspec. That's the problem I'm running into.

**Comment by maxkonovalov** [comment]
I also have a dependency for Chatto in my own lib's podspec, and the only way to make it work is by explicitly providing a version with a fix, because it's impossible to reference a specific branch for that case, just as @mbalex99 said.

@diegosanchezr @V0idPRO @geegaset can someone of you guys please push a new version to CocoaPods repo?

**Comment by AntonPalich** [comment]
New version 3.1.0 has been published

**Comment by v2Nitesh** [comment]
@jorgej-ramos - I have used github "badoo/Chatto" "master" in my Carthage file but I am facing the same issue. 

Carthage/Checkouts/Chatto/Chatto/Source/ChatController/BaseChatViewController+Presenters.swift:87:15: warning: parameter of 'collectionView(_:shouldShowMenuForItemAt:)' has different optionality than expected by protocol 'UICollectionViewDelegate'



Carthage/Checkouts/Chatto/Chatto/Source/ChatController/BaseChatViewController+Presenters.swift:95:15: warning: parameter of 'collectionView(_:canPerformAction:forItemAt:withSender:)' has different optionality than expected by protocol 'UICollectionViewDelegate'

As well as I have used the Chatto 3.1.0 version but still facing above warnings any suggestion? 

Thank you 
Nitesh
