### ISSUE TITLE
Chatto with live data downloaded through Alamofire

### ISSUE THREAD

**Issue by nalogowiec** [badoo/Chatto#314]
Hello, I've just checked Chatto and I really like it, I set up the example app that works on hardcoded data, now I would like to use it with my production data.

As for now I have a method that fetches all previous messages when user opens my view controller. This is how it looks like:

```
Alamofire.request("\(serverURL)/chats/\(roomId)/messages/\(page)/10")
    .validate()
    .responseJSON { response in
        switch response.result {
        case .success:
            DispatchQueue.main.async(execute: {
                
                var amount = 0
                if let jsonData = response.result.value as? [[String: AnyObject]] {
                    print(jsonData)
                    amount = jsonData.count
                    for requestJSON in jsonData {
                        
                        if let request = SingleMessage.fromJSON(JSON(requestJSON)){
                            self.messages.insert(request, at: 0)
                            
                        }
                    }   
                }
                self.collectionView?.reloadData()
                self.collectionView?.layoutIfNeeded()
                
            })
        case .failure(let error):
            print("SWITCH ERROR")
            
            print(error)
        }
        
}

```

It worked on my previous, self-coded approach to chat view.

Now, when I would like to switch to chatto, I see I need to start from populating the datasource.
I cannot find anywhere any tutorial of how to use chatto with live data, could you give me any hint about that?
Thanks!

**Comment by maxkonovalov** [comment]
Hi @nalogowiec, you can take a look at https://github.com/badoo/Chatto/wiki/Data-source

The main idea is that the fetching code should move from view controller to data source, where its `chatItems` should be populated and `chatDataSourceDidUpdate` should be called when appropriate.

**Comment by nalogowiec** [comment]
Is there a possibility of doing lazy loading (paging) of messages while using dynamic data source? I cannot make it work...

I'm fetching data through Alamofire:

```
Alamofire.request("\(serverURL)/chats/messages/\(page)/30")
    .validate()
    .responseJSON { response in
        switch response.result {
        case .success:
            DispatchQueue.main.async(execute: {
                
                var amount = 0
                if let jsonData = response.result.value as? [[String: AnyObject]] {
                    print(jsonData)
                    amount = jsonData.count
                    for requestJSON in jsonData {
                        if let request = SingleMessage.fromJSON(JSON(requestJSON)){
                            self.messages.insert(request, at: 0)
                        }
                    }
                }
                self.dataSource = FakeDataSource(messages: self.createMessages(messages: self.messages), pageSize: 10)
                self.chatDataSource = self.dataSource
                self.canFetchChats = true
                
            })
        case .failure(let error):
            print("SWITCH ERROR")
            
            print(error)
        }
        
    }

```

And I immediately see all 30 messages instead of first 10...

The problem is that in SlidingDataSource.swift there're those lines:

```
public convenience init(items: [Element], pageSize: Int) {
        self.init(count: 0, pageSize: pageSize, itemGenerator: nil)
        for item in items {
            self.insertItem(item, position: .bottom)
        }
    }

```

and it adds 30 messages at once... I would like to add first 10, and then when user scrolls up - reach method loadPrevious() from FakeDataSource, but now there's no way for it. It only loads everything at once and never calls loadPrevious(). What am I doing wrong?

**Comment by AntonPalich** [comment]
@nalogowiec I see that you load 30 messages from server, then you create data source with all of them. Try to download only 10, and then load more when user scrolls. 

Another option would be to implement your own data source. You really shouldn't use `FakeDataSource`. It was implemented for example app. In your own data source you can display only 10 items even if it stores 30 and then increase number of messages that you show to a user when user scrolls to the top.
