### ISSUE TITLE
NSInternalInconsistencyException, reason: 'Invalid update: invalid number of items in section 0

### ISSUE THREAD

**Issue by nalogowiec** [badoo/Chatto#317]
Sometimes I'm getting a weird error that crashes my app. It is a result of this code:

```
UIView.animate(withDuration: self.constants.updatesAnimationDuration, animations: { () -> Void in
                self.unfinishedBatchUpdatesCount += 1
                self.collectionView.performBatchUpdates({ () -> Void in
                    updateModelClosure()
                    self.updateVisibleCells(changes) // For instace, to support removal of tails

                    self.collectionView.deleteItems(at: Array(changes.deletedIndexPaths))
                    self.collectionView.insertItems(at: Array(changes.insertedIndexPaths))
                    for move in changes.movedIndexPaths {
                        self.collectionView.moveItem(at: move.indexPathOld, to: move.indexPathNew)
                    }
                }) { [weak self] (finished) -> Void in
                    defer { myCompletion() }
                    guard let sSelf = self else { return }
                    sSelf.unfinishedBatchUpdatesCount -= 1
                    if sSelf.unfinishedBatchUpdatesCount == 0, let onAllBatchUpdatesFinished = self?.onAllBatchUpdatesFinished {
                        DispatchQueue.main.async(execute: onAllBatchUpdatesFinished)
                    }
                }
            })
```

and my error says:

> 2017-05-21 17:24:24.269819 app[2468:723348] *** Assertion failure in -[UICollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3600.6.22/UICollectionView.m:5634
> 2017-05-21 17:24:24.270510 app[2468:723348] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of items in section 0.  The number of items contained in an existing section after the update (31) must be equal to the number of items contained in that section before the update (16), plus or minus the number of items inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).'
> *** First throw call stack:
> (0x1843551b8 0x182d8c55c 0x18435508c 0x184e0d02c 0x18ab0414c 0x18ab07c98 0x18ab07f78 0x18ab07dd8 0x18ab07d5c 0x18a3e4618 0x1012c822c 0x1012c7e20 0x18a2400f0 0x18a23fe68 0x1012c6bac 0x1012c8dc4 0x1012ce9f0 0x1012c99b4 0x1012ced48 0x1012c7e20 0x102a05258 0x102a05218 0x102a0a280 0x184302810 0x1843003fc 0x18422e2b8 0x185ce2198 0x18a2757fc 0x18a270534 0x1001a5dcc 0x1832115b8)
> libc++abi.dylib: terminating with uncaught exception of type NSException
> (lldb) 

Does anyone know what could be wrong here?

**Comment by lookitsatravis** [comment]
I'm also getting this error recently where I hadn't before. It looks like #142 has to do with the same error and the suggestion there is to make sure there are no duplicate items in the collection (same UID).

However, based on debug info, I know my collection does not contain any duplicate entries, so I'm not sure what else to look for. And, it's unclear why this started happening within the last few days of development, but never previously.

**Comment by AntonPalich** [comment]
@nalogowiec In general, this assertion triggered when data is inconsistent after update. In your crash log you had 16 rows before update, 31 rows after update, but there was no insertions. Usually it happens when you have items with same uid.
