### ISSUE TITLE
Receive history messages with Firebase

### ISSUE THREAD

**Issue by crazyfree** [badoo/Chatto#322]
Hi creators, 
First of all, thank you for awesome framework, it makes my life easier. 
Today, i tried to implement Chatto with Firebase and of course, trouble found me, LOL. Following is my issue.
In Firebase i just can receive history messages one by one using their API via `.childAdded` observer. And because i don't know what is last message so each message came, i have to call delegate `chatDataSourceDidUpdate` to present to screen, it's very slow, you know. It was a nightmare to me for debugging whole day. I think we can disable animation or something like that, but not sure. That's why i create this issue. 

Please help to deal with Firebase. Thank you so much.

**Comment by crazyfree** [comment]
I'm also wondering, how to calculate width height for image that returned from internet? i.e: Firebase in my case

**Comment by AntonPalich** [comment]
@crazyfree I never used Firebase, also I don't know your setup. But i've spent 5 minutes reading documentation and I see than you can get all messages at once by requesting specific path: https://firebase.google.com/docs/database/ios/read-and-write

Please, ask questions about Firebase on forums related to Firebase.

**Comment by fanghsia** [comment]
Fang Xia 赞了您的邮件。
Spark by Readdle
