### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by thepian** [badoo/Chatto#334]
The chattoapp doesn't seem to be working out of thebox. Itried to recreate the example as an alternative, but could not figure out how data source is supposed to be seeded. Where does it come from in the example

**Comment by AntonPalich** [comment]
@thepian Can you provider me more details? I was able to clone repo and run ChattoApp. Xcode9 and iOS 11 is not officially supported yet

**Comment by bayareahank** [comment]
Is it still the case with Xcode 9 and iOS 11? 

I tried to run the example app included in the latest source tree, with Carthage. Then build failed with message: 
Use of unresolved identifier 'BaseMessageDecorationAttributes" . 

An earlier version of last Nov works fine.

**Comment by AntonPalich** [comment]
@bayareahank Let's continue discussion in #435
