### ISSUE TITLE
Chatto failing in Swift source compatibility suite due to obsolete API usage

### ISSUE THREAD

**Issue by lplarson** [badoo/Chatto#335]
https://bugs.swift.org/browse/SR-5500

For example:
/Users/buildnode/jenkins/workspace-private/swift-master-source-compat-suite/project_cache/Chatto/Chatto/Source/ChatController/Collaborators/AccessoryViewRevealer.swift:59:29: error: 'addGestureRecognizer' has been renamed to 'add(_:)'
        self.collectionView.addGestureRecognizer(self.panRecognizer)
                            ^~~~~~~~~~~~~~~~~~~~
                            add

**Comment by jrose-apple** [comment]
Please do not act on this yet; we're pretty sure it's our bug.

**Comment by AntonPalich** [comment]
@jrose-apple, ok. Please, ping me when it become clear

**Comment by lplarson** [comment]
The failures were transient and are no longer occurring.
