### ISSUE TITLE
UI Crashing

### ISSUE THREAD

**Issue by SMFakhir** [badoo/Chatto#336]
Hi,

The UI is crashing straight when being used with photo cells. (It's working fine in 2.1.0)

The crash log says the main thread is not involved in updating UI, Any idea what could be the issue here?

I also got one of exception in layoutSubviews of BaseMessageCollectionViewCell.

**Comment by AntonPalich** [comment]
Are you using Xcode 9? It's not officially supported yet.

**Comment by SMFakhir** [comment]
No, I'm using 8.3.3

**Comment by AntonPalich** [comment]
@SMFakhir Can you provide full crash log?

**Comment by SMFakhir** [comment]
Sure

[issue_18_crash_8049e587cbbe4d77b66098a957f1be33_ab68d12e6e5811e7b04756847afe9799_0_v2.txt](https://github.com/badoo/Chatto/files/1166778/issue_18_crash_8049e587cbbe4d77b66098a957f1be33_ab68d12e6e5811e7b04756847afe9799_0_v2.txt)

**Comment by AntonPalich** [comment]
@SMFakhir SDWebImage triggers completion block not on the main thread. That's the reason. Make sure that you update view model in presenter in the main thread

**Comment by SMFakhir** [comment]
Got it, thanks. I should've inspected this earlier.
I thought it would be the main thread from SDWebImage but they have a good reason not to, not even noticed the thread on crash logs.

Much appreciated.
