### ISSUE TITLE
How to remove/delete message  bubble?

### ISSUE THREAD

**Issue by avinashsomashekar** [badoo/Chatto#351]
Hi,
I was able to implement custom UIMenuItem (delete). When i tried to delete the text message bubble and call chatDataSourceDidUpdate(:), the UICollectionView is not updated. Am i missing anything? Is there an easier way to implement this?
Appreciate your help.

**Comment by SarwarShoaib** [comment]
Hi @avinashsomashekar, I added `let item = UIMenuItem(title: "Delete", action: #selector(GPTextMessagePresenter.deleteMessage(_:)))
        UIMenuController.shared.menuItems = [item]` in `TextMessagePresenter` `open override func canShowMenu() -> Bool {
        return true
    }
    override func shouldShowMenu() -> Bool {
        return true
    }
    
    @objc
    public func deleteMessage(_ sender: Any?) {
    
    }
    
    open override func canPerformMenuControllerAction(_ action: Selector) -> Bool {
        if action.description == "deleteMessage:" {
            return true
        }}` but there is still no delete menu showing on message.
thank you.
