### ISSUE TITLE
ChattoApp Memory Leak 

### ISSUE THREAD

**Issue by rafattouqir** [badoo/Chatto#353]
Environment: Xcode 8.3.3, cocoapods-1.3.1
Chatto version : 3.1.0

Chatto framework in leaking memory in it's presenters.
I also run the ChattoApp and in instruments it's also leaking memory.

Any suggestion/fix would be appreciated

**Comment by munzuruleee** [comment]
Here is the some debug info:
![screen shot 2017-08-29 at 4 12 30 pm](https://user-images.githubusercontent.com/1902567/29816587-7ef9c700-8cd6-11e7-85f9-a68473cc765d.png)
![screen shot 2017-08-29 at 4 12 43 pm](https://user-images.githubusercontent.com/1902567/29816588-7f309f64-8cd6-11e7-950c-5dd92f017736.png)
![screen shot 2017-08-29 at 4 12 57 pm](https://user-images.githubusercontent.com/1902567/29816589-7f39631a-8cd6-11e7-9478-8787d44798c8.png)

**Comment by AntonPalich** [comment]
@rafattouqir, @munzuruleee Please, check https://github.com/badoo/Chatto/pull/357. There were leaks in example app, not in Chatto itself.

![image](https://user-images.githubusercontent.com/1708330/29838901-7152ed52-8cf4-11e7-9628-8bbd2a5e3955.png)
