### ISSUE TITLE
iOS11 messes with TextBubble interactionHandlers

### ISSUE THREAD

**Issue by timothytclee** [badoo/Chatto#363]
Just started testing on iOS11 devices.  It seems like the new gestures introduced in iOS11 are messing with the TextBubbleView gesture recognizers.  E.g. text selection inside a bubble is now possible.

Suspect the UITextView adjustments/hacks used in class ChatMessageTextView might need other work arounds.

**Comment by AntonPalich** [comment]
Hack with overriding `addGestureRecognizer(_:)` and filtering all unwanted recognizers doesn't work on iOS 11. Even if there is an empty implementation system somehow add them to UITextView.

Another approach would be to override `gestureRecognizers` property. Unfortunately, overriding setter doesn't give us desired effect but overriding getter works fine both on iOS 10 and iOS 11. I will do a pull request.

**Comment by Denismih** [comment]
On iPhone 7 , iOS 12 userDidEndLongPressOnBubble and userDidBeginLongPressOnBubble doesn't work on TextBubble. This gestures call UITextView popover menu only (Copy). How can I fix this?
