### ISSUE TITLE
Force Chattoo to reload

### ISSUE THREAD

**Issue by ogezue** [badoo/Chatto#37]
In my app I don't have Websockets (yet) so I periodically have to reload my datasource. I have adopted FakeDataSource from the ExampleApp to my needs:

```
 func reloadData(){
        dataModel.fetchNetworkingDetails(true, chatPartnerIdentifier: self.chatPartnerIdentifier, successHandler: { (networkingDetails: List<NetworkingDetail>) -> () in
            
            self.messages = networkingDetails
            self.nextMessageId = 0
            
            self.slidingWindow = SlidingDataSource(count: self.messages.count, pageSize: 500) { () -> ChatItemProtocol in
                
                defer { self.nextMessageId += 1 }
                
                let message = self.messages[self.nextMessageId]
                
                return MessageFactory.createChatItem(message)
            }
            
            }) { (error:ErrorType?) -> () in
        }
    } 
```

How can I enforce chattoo enforce to reload my data?

**Comment by diegosanchezr** [comment]
You just need to notify the view controller by calling `chatDataSourceDidUpdate(:)`

**Comment by ogezue** [comment]
Thanks! This is working. One speciality:
I have two types of cells: TextCells from Chattoo and my own Cells: AppointmentCells. 

I create the one or the other if my data object creates appointment data. The user can accept an appointment and then the appointment data will removed from the data object but the id stays the same. Is it possible that this causes this crash?
 
assertion failed: Invalid cell given to presenter: file /Pods/ChattoAdditions/ChattoAdditions/Source/Chat Items/BaseMessage/BaseMessagePresenter.swift, line 82

**Comment by diegosanchezr** [comment]
Yes, the framework doesn't support mutating from one cell/presesnter to another cell/presenter for the same uid. We are not sure if we are gonna ever support this. We could do

1) Add requirement for `Equatable` to ChatItem and generate a reload change when items are different: but this has issues: if you are using instances that mutate, they will be the same at the moment of comparing them so it won't work. If they are different, we may end generating a reload for a change that doesn't require it (the presenter/view model could listen for a property change and update the cell bypasing collection changes) so this can be bad for performance.
2) When dataSource updates we could just check if the presenter type for that item is the same as for the existing one; and just generate a reload change for that case. This would work as long as a presenter always uses only one type of cell.
3) Modifyng uid can be inconvenient. We may use uid+type as a key for generating changes and have the convention that mutating cell/presenter requires mutating uid+type

For the time being, I recommend you to mutate the uid for each case.

**Comment by ogezue** [comment]
Thank you - I solved it by changing the UID
