### ISSUE TITLE
Need to remove items under ExpandableTextView

### ISSUE THREAD

**Issue by charvoa** [badoo/Chatto#378]
Hi,

I just need to remove the UIScrollView under the ExpandableTextView (in ChatInputBar.xib) , but whenever I do this, I can't see the textview after , can you give me hints ? I need to do that because I only need the textfield, no other way of sending items (photo ...)

Thank you very much :)

**Comment by AntonPalich** [comment]
Hey @charvoa. Try to use your own input bar and return it in `createChatInputView()` function in your BaseChatViewController subclass.
