### ISSUE TITLE
Could not build Objective-C module 'ChattoAdditions'

### ISSUE THREAD

**Issue by saroar** [badoo/Chatto#384]
http://prntscr.com/h1dbw6
http://prntscr.com/h1dcbr

**Comment by saroar** [comment]
its xcode 9 with swift 4

**Comment by AntonPalich** [comment]
@saroar Did you sort it? Can you try to clean your build folder?

**Comment by saroar** [comment]
yes i try it then work thanks i like to ask two more qus 
1. is chatto is MVVM?
2. is there any example ios app with chatto back end websoket please if you know help send me link

**Comment by AntonPalich** [comment]
@saroar 
1. Chatto itself is not using MVVM. `BaseMessagePresenter` defined in `ChattoAdditions` module uses it. You can implement your own presenter by adopting`ChatItemPresenterProtocol` or subclass `BaseChatItemPresenter`. In your own implementation you can use whatever architecture you prefer.
2. I don't know any examples, sorry. But you can do it yourself. You have to provide `ChatDataSourceProtocol` implementation in `BaseChatViewController` subclass. This link may be useful for you: https://github.com/badoo/Chatto/wiki/Data-source In your implementation you can load messages in any way you want (using websocket, or Alamofire, or something else). The only thing you need to do is to trigger delegate function `chatDataSourceDidUpdate` when you load them
