### ISSUE TITLE
Swift 3.2 compile errors (ChattoAdditions)

### ISSUE THREAD

**Issue by egcode** [badoo/Chatto#387]
I updated my pods with ```pod update``` and I have these errors:

![badoocompileerrors](https://user-images.githubusercontent.com/12247313/32340647-7340e942-bfb8-11e7-9960-be9e0a9f776b.jpg)

Any clues?

**Comment by AntonPalich** [comment]
Hi @egcode. Looks like you updated to the latest commit in master with Swift 4 support, but your project compiles with Swift 3.2. Be sure that you point to Chatto 3.2.0, wich is the last version that supports Swift 3.2

**Comment by egcode** [comment]
Got it, thank you @AntonPalich.
