### ISSUE TITLE
Firebase Example

### ISSUE THREAD

**Issue by LisforLyance** [badoo/Chatto#388]
Is there another example project using Chatto open to the public? I looked at the Chatto-App and maybe I am just too stupid to get it, but I think that the Data Source part is a bit unclear and without any comments I don't get it. I already used firebase with the previous versions of my app and now after switching to Chatto I need to get it running somehow. I don't have enough time to worry about this for days, so an example with firebase would be awesome, but I would be also happy with something a bit clearer and more basic than the Chatto-App. Or maybe someone could just give me a hint or talk me through the steps I am missing. 
Well thanks in advance.

**Comment by saroar** [comment]
@LisforLyance hey there use my app with fire base may be it will help you 
https://github.com/saroar/RealtTimeIOSChat

best of luck

**Comment by LisforLyance** [comment]
@saroar Thank you very much. At first glance this already looks very helpful, but if I run into any problems I'll let you know.

**Comment by saroar** [comment]
u can run this app add me saroar@gmail.com then u can write me but i can write u only when i am in mac by simulator :) enjoy its Friday :)
