### ISSUE TITLE
3 Errors after migration to Swift 4

### ISSUE THREAD

**Issue by ebenj** [badoo/Chatto#389]
I got 3 errors when I accepted XCode 9 suggestion to migrate to Swift 4.

BaseMessageCollectionViewCellDefaultStyle: line 124
Cannot convert value of type '[NSAttributedStringKey : Any]' to specified type '[String : AnyObject]'

BaseMessageCollectionViewCellDefaultStyle: line 132
Cannot convert value of type '[String : AnyObject]' to expected argument type '[NSAttributedStringKey : Any]?'

LiveCameraCellPresenter: line 37
Static method 'createDefaultCameraAuthorizationStatusProvider()' is private and cannot be referenced from a default argument value

**Comment by x-hovo-x** [comment]
+1, @Badoo guys: do you have any idea when it will be moved to swift4 ?

**Comment by AntonPalich** [comment]
@ebenj , @x-hovo-x The latest master supports Swift 4.
