### ISSUE TITLE
Update message with UID 

### ISSUE THREAD

**Issue by charvoa** [badoo/Chatto#392]
I wanted to know if there was a way to update messages with their UID. I am using TCP and UDP for my text messages so the message arrives in multiple chuncks before getting updated, example : 

Receives : [Hi] 
Display : Hi
Receives : [dear]
Display : Hi, dear 
Receives : [friend, how are you]
Display : Hi, dear friend, how are you

And I would like to update my bubbles when I got the chuncks from my backend. 

Thanks for your help ..

**Comment by AntonPalich** [comment]
@charvoa Just trigger an update by calling `chatDataSourceDidUpdate` in your data source each time a message is updated. Ping me, if it doesn't help.
