### ISSUE TITLE
Errors on ChattoAddittions (Xcode 9, swift 4)

### ISSUE THREAD

**Issue by MussaCharles** [badoo/Chatto#399]
Hello, First thanks for this cool framework. I have issues with ChattoAdditions, my project fail to build due to the errors shown on the screenshot below. Is there any possible solution for this ?
ThankYou.
<img width="771" alt="podfileerrors" src="https://user-images.githubusercontent.com/25889447/32688716-8d410936-c719-11e7-8b7a-a76634f0788c.png">

**Comment by AntonPalich** [comment]
Yes. Your Podfile points to the latest master, I guess. It has Swift 4 support. If your project uses Swift 3.2, please point to 3.2.0 version.

**Comment by MussaCharles** [comment]
Thanks a lot @AntonPalich , I pointed to the latest master it now works fine .
