### ISSUE TITLE
Inserting element (TimeSeparator, SendingStatus ...) via DataSource results in a crash 

### ISSUE THREAD

**Issue by charvoa** [badoo/Chatto#412]
I'm having this issue : 
`
2017-12-01 15:07:52.781294+0100 APP-dev[2339:252944] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of items in section 0.  The number of items contained in an existing section after the update (57) must be equal to the number of items contained in that section before the update (55), plus or minus the number of items inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).'`

It's happening when I'm doing this : 

    
```

    /// DEmo chat controller 
    class ChatController: NSObject {
        static let shared = ChatController()
        
        private override init() {
            self.dataSource = DemoDataSource(count: 0, pageSize: 50)
        } // Static shared
        
        var dataSource: DemoDataSource? = nil
        var incomingUser: DemoChatUser? = nil
        var outgoingUser: DemoChatUser? = nil

        func updateTextMessageWith(uid: String,
                                   updatedItem: DemoTranscriptionItem,
                                   completion: @escaping ((Bool) -> Void)) {
            guard let dSource = self.dataSource else {
                completion(false)
                return
            }
            let items = dSource.slidingWindow.items
            for item in items {
                guard let rvItem = item as? DemoTextMessageModel else {
                    completion(false)
                    return
                }
                
                if item.uid == uid {
                    rvItem.text = updatedItem.text
                    
                    dSource.delegate?.chatDataSourceDidUpdate(dSource)
                    
                    completion(true)
                    return
                }
            }
            completion(false)
            return
        }
    }
    
    /// Demo Class Item 
    class ItemObject {
        var incoming: Bool = false
        var message: String = "Hello"
    }
    
    func updateTranscription(_ item: ItemObject) {
        // code
        print(item.text)
        let isIncoming: Bool = item.incoming
        
        if isIncoming == false {
            return
        }
        
        guard let dataSource = ChatController.shared.dataSource else {
            return
        }
        dataSource.addBotMessage("New Message :") //// NEW INSERTION OF BOT MESSAGE 
        ChatController.shared.updateTextMessageWith(uid: "\(item.uuid)", updatedItem: item) {
            success in
            if (success == false) {
                dataSource.addTextMessage(item, isIncoming: isIncoming)
            }
        }
    }
```
  
So whenever the updateTranscription is called (by my backend) with a new Item I call updateTextMessage, if the message already exists I replace the text, and when it doesn't exist I create the item (it's all done synchronously) And just before that (At line with the comment "//// NEW INSERTION OF BOT MESSAGE ")  I create a new ChatItem (of class BotMessage) which is a copy/paste of TimeSeparator except it contains a text and not a date. 

I don't know why I'm getting this error. Any help ?

Thanks guys !

**Comment by AntonPalich** [comment]
@charvoa It crashes because you have items with the same uid in your data source. Can you print all  items before you insert a new message here `dataSource.addTextMessage(item, isIncoming: isIncoming)`?

**Comment by charvoa** [comment]
@AntonPalich  YES that's it :o 

d8573711-d899-4cf9-adad-cb9d9f51a451-0-0
d8573711-d899-4cf9-adad-cb9d9f51a451-0-0

How should I change that ? ANd where ? because I don't remember setting this uid !

**Comment by charvoa** [comment]
@AntonPalich  even when I changed it I still have an error .. :'( 

f522a49b-4edc-463f-928a-ac825fa95d80-0-0-bot
f522a49b-4edc-463f-928a-ac825fa95d80-0-0

**Comment by charvoa** [comment]
@AntonPalich  Strange, when I remove the line dataSource.addTextMessage(item, isIncoming:isIncoming) I got this 

e2c9b6b2-4a98-4b1e-ac75-ea82d648a611-0-0
e2c9b6b2-4a98-4b1e-ac75-ea82d648a611-0-1
e2c9b6b2-4a98-4b1e-ac75-ea82d648a611-0-2

So every id is unique, but when I add it, I have duplicates and it crashes .. 

Thanks for the hint I will digg in that direction , but your help is still welcome haha

**Comment by charvoa** [comment]
So I digged. And my function updateText in my ChatController which looked like this : 

```
func updateTextMessageWith(uid: String,
                                   updatedItem: DemoTranscriptionItem,
                                   completion: @escaping ((Bool) -> Void)) {
            guard let dSource = self.dataSource else {
                completion(false)
                return
            }
            let items = dSource.slidingWindow.items
            for item in items {
                guard let rvItem = item as? DemoTextMessageModel else {
                    completion(false)
                    return
                }
                
                if item.uid == uid {
                    rvItem.text = updatedItem.text
                    
                    dSource.delegate?.chatDataSourceDidUpdate(dSource)
                    
                    completion(true)
                    return
                }
            }
            completion(false)
            return
        }
```

Now it looks like this : 

```
    func updateTextMessageWith(uid: String,
                               updatedItem: RVTranscriptionItem,
                               completion: @escaping ((Bool) -> Void)) {
        guard let dSource = self.dataSource else {
            completion(false)
            return
        }
        
        let items = dSource.slidingWindow.items
        for item in items {

            if item.uid == uid {
                if let rvItem = item as? RVTextMessageModel {

                rvItem.text = updatedItem.text

                dSource.delegate?.chatDataSourceDidUpdate(dSource)

                completion(true)
                return
                } else {
                    completion(false)
                }
            }
        }
        completion(false)
        return
    }
```

This part : 

   ```
             guard let rvItem = item as? DemoTextMessageModel else {
                    completion(false)
                    return
                }
```

Was totally wrong because my bot message is not a DemoTextMessageModel but a BotMessageModel, so it always returned false because it was the first entry. Dumb mistake that took me 4 hours ... 

Anyway, thanks for your help @AntonPalich  ! It was tremendous !
