### ISSUE TITLE
How to add additional MessageStatus?

### ISSUE THREAD

**Issue by Xopoko** [badoo/Chatto#418]
I want to extend this enum with additional cases like "sent, read, delivered". So, how can i do it?

**Comment by AntonPalich** [comment]
@Xopoko Do you want to modify messages state depending on additional cases or you just want to add text statuses under messages? Like this "Read" status:

![image](https://user-images.githubusercontent.com/1708330/33935348-867cb58a-dff3-11e7-88e6-44601c4bba68.png)

`MessageStatus` is used to determine messages appearance in different states. For example, it is used to choose an appropriate bubble colour and to show an additional overlay on photo messages. If you want to modify messages appearance based on additional states, then you can't reuse existing base cell implementation. You have to implement a hierarchy of classes for your new base message cell: `CustomBaseMessagePresenter` and `CustomBaseMessageCollectionViewCell`. If you want to follow the same way as it's done in `BaseMessageCollectionViewCell`, then additionally you have to implement a view model and a style for your new base message cell. However, you can reuse existing text and photo bubbles, they're just views.

If you want to add a text status under message it's is much easier to do. You can implement it as an additional chat item, check this link: https://github.com/badoo/Chatto/wiki/Tutorial_Add_Custom_Cell

You can add those statuses in your ChatItemsDecoratorProtocol implementations. It takes chat items as input and returns decorated chat items as output. In Badoo we add all statuses during decoration.

**Comment by Xopoko** [comment]
@AntonPalich Thank you so much. It really helpful for me. Thank!
