### ISSUE TITLE
shouldShowMenu() assert failure on long press

### ISSUE THREAD

**Issue by bcamur** [badoo/Chatto#42]
Hi, when I send a new message and try to copy it sometimes my app crashes in this function:
```
    public override func shouldShowMenu() -> Bool {
        guard self.canShowMenu() else { return false }
        guard let cell = self.cell else {
            assert(false, "Investigate -> Fix or remove assert")
            return false
        }
        cell.bubbleView.userInteractionEnabled = false // This is a hack for UITextView, shouldn't harm to all bubbles
        NSNotificationCenter.defaultCenter().addObserver(self, selector: "willShowMenu:", name: UIMenuControllerWillShowMenuNotification, object: nil)
        return true
    }
```

I have been investigating but couldn't find anything, do you have any ideas?

**Comment by diegosanchezr** [comment]
Hi @bcamur, try dev branch; it shouldn't happen there.

**Comment by bcamur** [comment]
dev branch did solve the problem indeed :) Thanks for the help. Are there any significant changes I should be aware of in the dev branch btw?

**Comment by diegosanchezr** [comment]
You can see changes [here](https://github.com/badoo/Chatto/issues?utf8=%E2%9C%93&q=base%3Adev+) (your bug was fixed in https://github.com/badoo/Chatto/pull/36)

At this moment, the biggest changes are that bugfix and more API made public. dev branch is likely to become Chatto 2.0. It can be unstable and break API so use it carefully ;)

**Comment by bcamur** [comment]
Thank you again. I guess its better to keep up with the changes as they arise rather than a big transition from v1 to v2. I really appreciate the work you did here, great engineering ;) (Closing the issue btw)
