### ISSUE TITLE
Chatto Additions latest version is not updated yet

### ISSUE THREAD

**Issue by mukulm24** [badoo/Chatto#427]
It gives me many syntax errors on version 3.2.0 of Chatto Additions using Xcode 9.1

**Comment by tapparello** [comment]
Is anyone working on this? I have the same issue in Xcode 9.2

**Comment by AntonPalich** [comment]
@mukulm24, @tapparello Please, check this comment: https://github.com/badoo/Chatto/issues/331#issuecomment-351670462
