### ISSUE TITLE
Change 4b094c2 breaks example app's build 

### ISSUE THREAD

**Issue by bayareahank** [badoo/Chatto#435]
Change 4b094c2 (Extracted parameters from ChatItemDecorationAttributes related to BaseMessageDecorationAttributes). introduces  new data struct BaseMessageDecorationAttributes, and example app's source is updated to utilize it. Yet this happened after 3.2.0.,  so Carthage build, which pulls 3.2.0 automatically, would fail to recognize this data structure, causing build failure

We should either bump up 3.2.0 version, or do some other remedy to make the example app work again. (MAGA, lol).

**Comment by AntonPalich** [comment]
@bayareahank Can you provide more details? I tried to build Chatto with Carthage and it works fine for me.

Cartfile:

`github "badoo/Chatto"`

Console output:

```
[18:59] antonschukin:~/Dev/Chatto_Carthage $ carthage update
*** Cloning Chatto
*** Checking out Chatto at "3.2.0"
*** xcodebuild output can be found in /var/folders/r9/98414sfx6hbfvpnj4_h91zr80000gp/T/carthage-xcodebuild.8JYzm9.log
*** Building scheme "Chatto" in Chatto.xcworkspace
*** Building scheme "ChattoAdditions" in Chatto.xcworkspace
```

After that I opened `Carthage/Checkouts/Chatto/ChattoApp/ChattoApp.xcworkspace` and build `ChattoApp` target. I didn't see any compilation issues

**Comment by bayareahank** [comment]
Can you check source file under the example app Carthage directory at ./Carthage/Checkouts/Chatto/ChattoAdditions/Source/Chat Items/ChatItemDecorationAttributes.swift and see whether it contains definition of struct BaseMessageDecorationAttributes? BTW, this checkout should be purely 3.2.0 source code. 

I repeated the carthage build procedure again, and I can see the difference of Chatto 3.2.0's ChatItemDecorationAttributes.swift and main branch's. While the main branch one has definition for BaseMessageDecorationAttributes, the 3.2.0 doesn't.  At the same time, this struct is used inside the example app at: ChattoApp/Source/Chat View Controllers/DemoChatItemsDecorator.swift. That would make the example app fail. 

As to your build success, I am suspecting it could be a build path setting issue. I am thinking with your setup, somehow the builder was able to find an up-to-date ChattoAddtions lib that contains the new struct definition, since your environment should have success build with the latest data struct definition. Yet for fresh checkout, it may not be able to. I have seen similar things with C/C++ build before, but I am not an expert with swift build.

**Comment by bayareahank** [comment]
BTW, I assume that you already know that you need to add the framework built by 'carthage update' to the 'linked frameworks and libraries' section under project's 'general' tab. And also to get rid of the stuff related to pod. Otherwise the default build may still use libraries provided by pod, not carthage. I am suspecting that could be a cause here. FYI.

**Comment by AntonPalich** [comment]
@bayareahank `DemoChatItemsDecorator` exists only in the demo app in the master branch. In the 3.2.0 version, it's called `ChatItemsDemoDecorator` and it doesn't use `BaseMessageDecorationAttributes`. If you open example app from `Carthage/Checkout/Chatto/ChattoApp` folder you won't find `DemoChatItemsDecorator` here.

I think you're trying to put framework build for 3.2.0 into demo app from the master branch. It won't work. Try to put the framework into demo app from 3.2.0. It worked for me. My steps:

1. Open ChattoApp.xcodeproj (not a workspace)
2. Remove Pods frameworks from Frameworks folder
3. Remove Pods xcconfigs from Pods folder
4. Remove build phases with [CP] prefix
5. Add Chatto.framework and ChattoAdditions.framework from `Carthage/Build/iOS` folder
6. Compile

**Comment by bayareahank** [comment]
It is exactly as you said. But the thing is, if you try to compile master branch using Carthage, it will pull in 3.2.0 branch's code, and thus not working. This is the root cause, that is the reason I am suggesting to bump up existing version, so carthage build of master branch can work.

**Comment by AntonPalich** [comment]
I see. Unfortunately, I can't bump version yet. It will be done in the next weeks. We have to do some tasks before releasing a new version that supports Swift 4.

Until then you can use "master" branch in Cartfile.
