### ISSUE TITLE
Scroll to specific Message Item

### ISSUE THREAD

**Issue by seidju** [badoo/Chatto#437]
Hi @AntonPalich , I want to implement Reply functionality, so user, after he taps on "replied" message scrolls to original message.
The main problem is, that sliding data source doesn't give me all items at once, so before scrolling, I need to add messages to dataSource, something like this: 
```swift
func loadPrevious(completion: (() -> ())?) {
    slidingWindow.loadPrevious()
    slidingWindow.adjustWindow(focusPosition: 0, maxWindowSize: preferredMaxWindowSize)
    delegate?.chatDataSourceDidUpdate(self, completion: completion) //add completion block for dataSource update
  }
```
Now, I call something like recursively append images to SlidingDataSource, until desired `messageId` would contains in `chatItems` :
```swift
fileprivate func scrollToItem(index: Int, messageId: String) {
    if dataSource.chatItems.contains(where: { $0.uid == messageId }) {
      let ip = IndexPath(item: index, section: 0)
      //scroll ???
    } else {
      dataSource.loadPrevious { [weak self] in
        self?.scrollToItem(index: index, messageId: messageId)
      }
    }
  }
```
My question - how to scroll to this message, even if it's already in `chatItems`. I tried to just use 
```swift
      collectionView.scrollToItem(at: ip, at: .centeredVertically, animated: true)
```
but I got an error ,that cell at `ip` is doesn't exist.
Thanks for any help or advice!

**Comment by Xopoko** [comment]
Same question. Has anyone already been able to fix it? The issue has been open since February 6.

**Comment by spacedema** [comment]
Have the same issue. Any workaround?

**Comment by Daxito** [comment]
+1

**Comment by seidju** [comment]
Hi everyone! Any updates on this issue. I tried on latest release, using `scrollToItem(withId: uid)`, but still no effect. In this function - property `            let isScrollingUp = rect.minY < collectionView.contentOffset.y
`

**Comment by AntonPalich** [comment]
@seidju I just checked the demo app. I modified `handleTapOnScrollToBottomButton` function to scroll to the first item when you tap "Scroll to bottom" button on "Scroll To Bottom Button Example"  screen. It worked for me.

```swift
    @objc
    private func handleTapOnScrollToBottomButton() {
        guard self.chatItemCompanionCollection.count > 0 else { return }

        let startIndex = self.chatItemCompanionCollection.endIndex
        self.scrollToItem(withId: self.chatItemCompanionCollection[startIndex].uid, position: .top, animated: true)
    }
```

Having `isScrollingUp == false` doesn't mean that it doesn't work. Your item can be visible on a  screen, or you have not enough items to make a scroll action. Could you provide a list of items when you try to scroll, a screen from your app and id of a `messageModel.uid`?

**Comment by seidju** [comment]
@AntonPalich Yep, I just checked it again and it was my stupid mistake (used wrong `uid`). Everything works great, as expected.  Sorry for that )
Closing this issue!
