### ISSUE TITLE
How to change spacing between custom chat cells?

### ISSUE THREAD

**Issue by thebrankoo** [badoo/Chatto#441]
What is the best way to change spacing between custom made chat cells?  I need to eliminate spacings.

**Comment by LukA888** [comment]
Hi! 

The chat decorator has always the last word and you have to configure your wanted spacing for your cells there. 

You can check the functionality in the demo app: https://github.com/badoo/Chatto/blob/master/ChattoApp/ChattoApp/Source/Chat%20View%20Controllers/DemoChatItemsDecorator.swift#L106
