### ISSUE TITLE
iOS 10 Compatibility

### ISSUE THREAD

**Issue by MikeSalvador** [badoo/Chatto#448]
Is Chatto compatible with iOS 10? I'm having issues compiling when I set the build target to 10.0.

**Comment by AntonPalich** [comment]
@MikeSalvador It's compatible with iOS 10. What kind of issue do you have? It compiles for me in the demo app

**Comment by MikeSalvador** [comment]
Sorry, I should have been more specific. So it's not archiving, but I'm able to run it on my iPhone. The error I'm getting is when I try to import Chatto, it's saying 'No such module 'Chatto'

**Comment by MikeSalvador** [comment]
This error started showing up after I changed my deployment target from 11.0 to 10.0.

**Comment by MikeSalvador** [comment]
Just had to reinstall the Chatto/ChattoAdditions pods.
