### ISSUE TITLE
space between cells

### ISSUE THREAD

**Issue by baldemir** [badoo/Chatto#449]
Hi,

Firstly thanks for such a useful framework. After i integrated your framework from demo to my app i have 0 spaces between cells. It looks a bit bad. I googled about how to fix that but couldn't find a proper way. Is there anyone who can tell me how can i increase this space? I'm talking about vertical space when user sends consecutive messages.

<img width="275" alt="screen shot 2018-02-19 at 22 41 13" src="https://user-images.githubusercontent.com/7359315/36394532-cd81d610-15c5-11e8-87c8-8597cc1e52e4.png">

**Comment by AntonPalich** [comment]
Thanks @LukA888
