### ISSUE TITLE
Input bar during first opening does not follow safeArea on iPhone X.

### ISSUE THREAD

**Issue by alexanderkhitev** [badoo/Chatto#451]
Please have a look
![iphone x - 11 2 2018-02-20 22-51-28](https://user-images.githubusercontent.com/12511909/36442943-c68121d8-1690-11e8-906f-cc78e556f860.png)

**Comment by alexanderkhitev** [comment]
Hi @AntonPalich ! I  deleted everything from the `setupInputContainerBottomConstraint` function except `self.inputContainerBottomConstraint.constant = self.bottomLayoutGuide.length`  and it does not break UI if used with `TabBar`. Please comment on this.

**Comment by AntonPalich** [comment]
@alexanderkhitev Consider applications that use tab-bar everywhere but chat. They want to hide it when chat is opened. Does this case still work after your changes?

**Comment by alexanderkhitev** [comment]
@AntonPalich I will write to you in some time, as I will check. But the current code breaks the following script, the UITabBarController application has a rootViewController, when we go to ChatViewController and set the following value to hidesBottomBarWhenPushed = true, then we get the result which is in the screenshot above.

**Comment by alexanderkhitev** [comment]
@AntonPalich it breaks even ChattoApp. Please have a look at https://monosnap.com/file/2f6jGpYNWsRvhXptRjqLyslGKy61DR

**Comment by alexanderkhitev** [comment]
@AntonPalich I sent a new pull request, I did a manual test, everything works as in the demo project and in our project. You can watch the video.

**Comment by apwelsh** [comment]
How did you fix this?  In my app, I remove the TabBar, and the bottom of the Chat View, which was pushed, is still starting at the top of the TabBar, not the bottom of the safe area.  This is driving me crazy.
