### ISSUE TITLE
Support photo gallery 

### ISSUE THREAD

**Issue by geideaiosapps** [badoo/Chatto#455]
Is there any capability to add collection view inside chatting like the attached screenshots and alert actions ?

![screen shot 2018-02-22 at 11 18 22 am](https://user-images.githubusercontent.com/36667715/36527466-ea45ae8a-17c2-11e8-9146-f30f6eabbd02.png)
![screen shot 2018-02-22 at 11 15 17 am](https://user-images.githubusercontent.com/36667715/36527467-ea67d320-17c2-11e8-934b-3b7ff99ee5df.png)

**Comment by AntonPalich** [comment]
@geideaiosapps You may have any kind of custom items in a chat, including other collection views (that will be a simple cell that contains collections view as a content). You can check this small tutorial: https://github.com/badoo/Chatto/wiki/Tutorial_Add_Custom_Cell
