### ISSUE TITLE
Chatto 3.2.0 from CocoaPods not compiling

### ISSUE THREAD

**Issue by pablosproject** [badoo/Chatto#456]
I have added chatto as dependency in my Podfile, and when using the tag 3.2.0 the project is not compiling.
The only way to get it working is to use the version pointing directly to master.

**Comment by sergdort** [comment]
Same

**Comment by AntonPalich** [comment]
@pablosproject , @sergdort  https://github.com/badoo/Chatto/issues/331#issuecomment-351670462
