### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by Daxito** [badoo/Chatto#459]
I am getting this error, am I missing something? Thanks!

![image](https://user-images.githubusercontent.com/16787057/37037496-0bb0c7e0-2118-11e8-9026-9005246cfb0d.png)

**Comment by alamyudi** [comment]
Hi @Daxito , i also have some problem, i do some point below to resolve that : 
1. change the swift language compiler from 4.0 to 3.2 
2. clean project
3. run `pod install`

<img width="746" alt="screen shot 2018-03-08 at 16 39 35" src="https://user-images.githubusercontent.com/839045/37144101-a00e13ce-22ef-11e8-8ad0-49c58c7468f7.png">

**Comment by Daxito** [comment]
Thank you @alamyudi , but I have to use Swift 4.0, if I use:
pod 'Chatto', :git => 'https://github.com/badoo/Chatto', :branch => 'master'
pod 'ChattoAdditions', :git => 'https://github.com/badoo/Chatto', :branch => 'master'

Then it is fine.
