### ISSUE TITLE
Subclassing BaseMessageCollectionViewCell

### ISSUE THREAD

**Issue by bcamur** [badoo/Chatto#46]
Hi, I'm trying to subclass BaseMessageCollectionViewCell as you did with TextMessageCollectionViewCell and PhotoMessageCollectionViewCell, however even if I try to copy all of the code of TextMessageCollectionViewCell and rename it to something else I get several compiler errors such as: "Initializer does not override any method from its superclass". 
Actually all I need to override is `canPerformAction(action: Selector, withSender sender: AnyObject?) -> Bool` function and add some methods for custom edit menu actions. I tried to do this in an extension of TextMessageCollectionViewCell but apparently Swift doesn't let me override canPerformAction in an extension. Do you have any suggestions or workarounds for this problem. Or any other way to add custom items to edit menu of chat bubbles. Thanks.

**Comment by diegosanchezr** [comment]
Inheriting from BaseMessageCollectionViewCell is missing public access level for init(frame:) and createBubbleView() so they can't be inherited outside ChattoAdditions module as I mentioned in https://github.com/badoo/Chatto/issues/26. Can you try that locally and make a PR if it works?

**Comment by bcamur** [comment]
Do you mean changing those methods to `public`? And by working do you mean if I can subclass ChattoChatViewController outside of ChattoAdditions? If your answer to both of these questions are 'yes', I would be more than happy to attempt to contribute to Chatto.

**Comment by diegosanchezr** [comment]
Yes, I mean changing those methods to public and verifying it solves your problem (that you can subclass the cells). ChatViewController has no problems being subclassed (it's done in ChattoApp)

**Comment by bcamur** [comment]
Just finished the work after struggling with Xcode for hours :/ With the changes in #48 I can successfully subclass BaseMessageCollectionViewCell.

**Comment by diegosanchezr** [comment]
@bcamur thank you!

**Comment by bcamur** [comment]
You are welcome, and thank you; this was my first PR and contribution to an OSS project :)
