### ISSUE TITLE
Text containing CLRF doesn't render on iPad in some cases

### ISSUE THREAD

**Issue by borkuslav** [badoo/Chatto#463]
When I test specific multiline texts that contain "'r\n" or "\n", `UITextView` in `TextBubbleView`  doesn't display text, for instance adding this text: 

`"acon ipsum dolor amet short ribs tri-tip pig, porchetta turkey alcatra shoulder meatloaf tenderloin meatball biltong swine. Rump sirloin beef, landjaeger corned beef venison sausage flank t-bone pork loin prosciutto. Ribeye landjaeger leberkas kielbasa, sausage hamburger t-bone andouille pastrami picanha chicken. Tri-tip jowl ham salami fatback shank, pork loin ball tip. Filet mignon swine t-bone, pork loin tri-tip corned beef cupim kevin pork belly beef ribs.\r\nCow ball tip bresaola ham pork loin, tongue bacon flank pork chop capicola kielbasa boudin strip steak. Beef ribs pork belly"`

to the `overviewMessages` array in `DemoChatMessageFactory` results in this on iPad Sim iOS 11.2:
<img width="388" alt="zrzut ekranu 2018-03-12 o 16 58 20" src="https://user-images.githubusercontent.com/12987442/37294650-9a291e8e-2616-11e8-86b2-cefee012bbcc.png">
while it works good on all iPhones:
<img width="284" alt="zrzut ekranu 2018-03-12 o 16 55 35" src="https://user-images.githubusercontent.com/12987442/37294685-b3304b82-2616-11e8-9a0b-e41b99acccf6.png">
Exactly the same behaviour on real devices. In some cases adding line
`textView.setNeedsUpdateConstraints()` at the end of `TextBubbleView::updateTextView` method fixes it for some cases but not in all. 

I would contribute with pleasure to this great project, but unfortunately I wasn't able to find solution.

**Comment by AntonPalich** [comment]
@borkuslav I checked this text in the demo app and it works for me. Do you have any other changes in your example?

![simulator screen shot - ipad air 2 - 2018-03-12 at 16 34 49](https://user-images.githubusercontent.com/1708330/37296670-9222433a-2613-11e8-9a4a-a2a719a370b3.png)

**Comment by borkuslav** [comment]
Oh, sorry, I pasted example containing "\n\n" which works fine, I replaced that in the text above with "\r\n" which doesn't work. Please try again.

**Comment by AntonPalich** [comment]
@borkuslav Looks like #364 fixes this issue. I will merge it
