### ISSUE TITLE
Plan to support Carthage?

### ISSUE THREAD

**Issue by zwang** [badoo/Chatto#5]
Hi Badoo Team

Thanks a lot for this awesome library. 

I have read the Readme and the blog post on your website. I also spent some time on the the` Chatto` project source code. It seems to be very well architected too. I am planning to use this in my project. However, it seems carthage not supported for now since I want to use both `Chatto` and `ChattoAdditions`. Do you have an estimate when carthage will be supporting two framework build from the same repo or do you have a plan to make Chatto(+Additions) carthage compatible? Maybe by separating them into different repo or combining them to one repo?

I think it might be a good idea to make them separate repos for now. So people still have the flexibility to only include `Chatto`. Are there any concerns of not keeping them in the same repo?

Thanks again!

**Comment by Chiliec** [comment]
+1

**Comment by diegosanchezr** [comment]
We do want to support carthage, but not at the cost of splitting the repo or merging the frameworks.  I opened issue https://github.com/Carthage/Carthage/issues/991 to see whether this restriction can be fixed.
