### ISSUE TITLE
Compile error: Header 'ChattoAdditions-Swift.h' not found

### ISSUE THREAD

**Issue by vasadulin** [badoo/Chatto#504]
I use Chatto and ChattoAdditions successfully in swift project, XCode 9.2. with Cocoa Pods.
I updated Xcode to version 9.4.1. 
There was  an errors in automatic generated file "module.modulemap": 
Header 'ChattoAdditions-Swift.h' not found.

There is not  'ChattoAdditions-Swift.h' file in repository.
How to fix this error? 

![chattoerror](https://user-images.githubusercontent.com/1208018/43711882-e18822c8-997c-11e8-9a72-0a467af20d9b.png)

**Comment by AntonPalich** [comment]
@vasadulin I'm pretty sure there is an issue with Swift versions. Can you take a look into this comment? https://github.com/badoo/Chatto/issues/331#issuecomment-351670462 It should help

**Comment by vasadulin** [comment]
To fix this error:

Increase the version of Swift for the libraries: Chatto and ChattoAdditions.

The main project has swift 3.3 version. But I can use libraries with swift 4.

Steps to fix problem:

- Choose Pods in Project navigator.
- Choose target: ChattoAdditions (Chatto)
- Change Swift Language Version to Swift 4.1
- Rebuild project (Clean & Build)

![chattofix](https://user-images.githubusercontent.com/1208018/43762336-5366cd14-9a30-11e8-98e0-3149ee149f89.png)

**Comment by AntonPalich** [comment]
@vasadulin If you do it manually then you need to do it every time you update pods. I suggest you to add a script from the comment above to the end of your podfile.
