### ISSUE TITLE
Adding extra view to the ChatViewController for setting participants

### ISSUE THREAD

**Issue by weyert** [badoo/Chatto#51]
I would like to add a visual element to allow defining the participants of the chat. Only when I try to add my view with the appropriate constraints it's not working for me. I am descending from the ChatViewController class and then add a view, like this, in the `viewDidLoad`-method:

`self.view.addConstraint(NSLayoutConstraint(item: participantsInputBar, attribute: .Left, relatedBy: .Equal, toItem: self.view, attribute: .Left, multiplier: 1.0, constant: 0))
            self.view.addConstraint(NSLayoutConstraint(item: participantsInputBar, attribute: .Width, relatedBy: .Equal, toItem: self.view, attribute: .Width, multiplier: 1.0, constant: 0))
            self.view.addConstraint(NSLayoutConstraint(item: participantsInputBar, attribute: .Top, relatedBy: .Equal, toItem: self.topLayoutGuide, attribute: .Bottom, multiplier: 1.0, constant: 0))
            self.view.addConstraint(NSLayoutConstraint(item: participantsInputBar, attribute: .Bottom, relatedBy: .Equal, toItem: self.view, attribute: .Bottom, multiplier: 1.0, constant: 0))
`
It's showing up directly below the navigation bar but the chat window is showing up below this element. I don't want this. How can I fix this? I am doing something wrong?

<img width="350" alt="screen shot 2016-03-06 at 16 23 42" src="https://cloud.githubusercontent.com/assets/7049/13555413/d9fcbf28-e3b7-11e5-9394-b32ff3fbebc4.png">

**Comment by weyert** [comment]
Anyone having any suggestions?

**Comment by diegosanchezr** [comment]
Hi @weyert, If you upload a sample project with the issue I may be able to take a look.

**Comment by weyert** [comment]
@diegosanchezr I will try to reproduce the problem with the ChattoApp :)

**Comment by weyert** [comment]
@diegosanchezr Please find the issue at hand in the ChattoApp: 
https://github.com/weyert/Chatto/tree/dev

I would like not to be able to scroll under the address bar view. I would expect that the little scrollbar indicators would stop before the address bar instead of going below the address bar. Am I am doing something wrong? Do I misunderstand the behaviour of the scroll or collection view regarding this?

**Comment by diegosanchezr** [comment]
Hi @weyert. Take a look at this

If you want to change the collection view position so it starts bellow your header:

```swift
override func viewDidLoad() {
    super.viewDidLoad()
    let headerView = UIView()
    headerView.translatesAutoresizingMaskIntoConstraints = false
    headerView.backgroundColor = UIColor.greenColor()
    self.view.addSubview(headerView)
    self.view.addConstraint(NSLayoutConstraint(item: headerView, attribute: .Height, relatedBy: .Equal, toItem: nil, attribute: .NotAnAttribute, multiplier: 1, constant: 50))
    self.view.addConstraint(NSLayoutConstraint(item: headerView, attribute: .Top, relatedBy: .Equal, toItem: self.topLayoutGuide, attribute: .Bottom, multiplier: 1, constant: 0))
    self.view.addConstraint(NSLayoutConstraint(item: headerView, attribute: .Left, relatedBy: .Equal, toItem: self.view, attribute: .Left, multiplier: 1, constant: 0))
    self.view.addConstraint(NSLayoutConstraint(item: headerView, attribute: .Width, relatedBy: .Equal, toItem: self.view, attribute: .Width, multiplier: 1, constant: 0))
    self.collectionView.removeFromSuperview()
    self.view.insertSubview(self.collectionView, atIndex: 0)
    self.view.addConstraint(NSLayoutConstraint(item: self.collectionView, attribute: .Top, relatedBy: .Equal, toItem: headerView, attribute: .Bottom, multiplier: 1, constant: 0))
    self.view.addConstraint(NSLayoutConstraint(item: self.view, attribute: .Leading, relatedBy: .Equal, toItem: self.collectionView, attribute: .Leading, multiplier: 1, constant: 0))
    self.view.addConstraint(NSLayoutConstraint(item: self.view, attribute: .Bottom, relatedBy: .Equal, toItem: self.collectionView, attribute: .Bottom, multiplier: 1, constant: 0))
    self.view.addConstraint(NSLayoutConstraint(item: self.view, attribute: .Trailing, relatedBy: .Equal, toItem: self.collectionView, attribute: .Trailing, multiplier: 1, constant: 0))
}
```
```swift
override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()
    self.collectionView.contentInset.top = 0
    self.collectionView.scrollIndicatorInsets.top = 0
}
```
If you don't want to change the collection view frame (so cells will be visible under translucent views on scrolling) then it's just:
```swift
override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()
    self.collectionView.contentInset.top = self.topLayoutGuide.length + headerHeight
    self.collectionView.scrollIndicatorInsets.top = self.topLayoutGuide.length + headerHeight
}
```

**Comment by weyert** [comment]
Awesome, that's great. Thank you! 
Should buy you a drink in Soho ;)
