### ISSUE TITLE
Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by gavinong23** [badoo/Chatto#512]
`   
    lazy private var baseMessageHandler: BaseMessageHandler = {
        return BaseMessageHandler(messageSender: self.messageSender, messagesSelector: self.messagesSelector)
    }()`

why i get Thread 1: Fatal error: Unexpectedly found nil while unwrapping an Optional value... Although i follow all the sample code.

**Comment by OxyFlax** [comment]
Could you please tell us how you managed to fix this issue?
