### ISSUE TITLE
Update for Xcode 10 and Swift 4.2

### ISSUE THREAD

**Issue by dastan28** [badoo/Chatto#516]
Hi!
Any plans to update libraries for Xcode 10 and Swift 4.2?

**Comment by Daxito** [comment]
+1

**Comment by TheRebelMan** [comment]
+2

**Comment by rohaaa** [comment]
+100500

**Comment by AntonPalich** [comment]
Yes guys, we have a plane to add support for Xcode 10 and Swift 4.2. I hope we will do it in the next week.

**Comment by OneSman7** [comment]
Any updates on the timeframe for Swift 4.2 support?

**Comment by AntonPalich** [comment]
@OneSman7 I'll push swift_4.2 branch tonight

**Comment by AntonPalich** [comment]
`swift_4.2` branch is here. You can check changes in #521 PR. Let me know if something is wrong. This branch won't be merged into master and won't have a version for a while until Badoo migrate to Swift 4.2 and Xcode 10 but you can use it if you already migrated.

**Comment by xakacuk** [comment]
i use:
  pod 'Chatto', :git => 'https://github.com/badoo/Chatto', :branch => 'master'
  pod 'ChattoAdditions', :git => 'https://github.com/badoo/Chatto', :branch => 'master'
and i have many errors

**Comment by AntonPalich** [comment]
@xakacuk You should use `swift_4.2` branch

```
pod 'Chatto', :git => 'https://github.com/badoo/Chatto', :branch => 'swift_4.2'
pod 'ChattoAdditions', :git => 'https://github.com/badoo/Chatto', :branch => 'swift_4.2'
```

**Comment by saroar** [comment]
@AntonPalich can i use same
```
pod 'Chatto', :git => 'https://github.com/badoo/Chatto', :branch => 'swift_4.2'
pod 'ChattoAdditions', :git => 'https://github.com/badoo/Chatto', :branch => 'swift_4.2'
now

**Comment by AntonPalich** [comment]
Branch is in master
