### ISSUE TITLE
Constraint issue in iphone x

### ISSUE THREAD

**Issue by nehatyagi18** [badoo/Chatto#520]
![simulator screen shot - iphone xs - 2018-10-03 at 10 14 45](https://user-images.githubusercontent.com/43131293/46390428-647cfc80-c6f5-11e8-89cf-cc42def287c0.png)
I am facing this issue in iphone x and iphone xs just because of NSLayoutConstraint

**Comment by AntonPalich** [comment]
@nehatyagi18 You can change color of `BaseChatViewController.bottomSpaceView` that should fill bottom safe area. By default, it's has white color. Don't know what happened in your case. Can you check your view hierarchy?

**Comment by nehatyagi18** [comment]
bottomSpaceView not found in BaseChatViewController. Please check screenshot. This is issue of collectionView. It should not be down to textview. I am using 3.1.0 version of chatto.

**Comment by Ogerets** [comment]
@nehatyagi18 You use 2 years old version of library and reporting an issue on it, am I right? Are you serious?

**Comment by nehatyagi18** [comment]
Yeah!! i know that i am using older version. Now i am asking if i will update to latest version of chatto than this issue will not come.

**Comment by AntonPalich** [comment]
@nehatyagi18 Could you, please, update to the latest version where this issue is already fixed?
