### ISSUE TITLE
Chat Additions /UIKit.UIApplication:5:20: 'shared' has been explicitly marked unavailable here

### ISSUE THREAD

**Issue by chihung93** [badoo/Chatto#534]
Swift : 4.2
Xcode: Version 10.1 (10B61)
I can't run project because of this error on branch swift 4.2.
Thanks.
Chat Additions /UIKit.UIApplication:5:20: 'shared' has been explicitly marked unavailable here
<img width="775" alt="screen shot 2018-11-22 at 2 54 00 pm" src="https://user-images.githubusercontent.com/5199109/48888835-7d3c9f80-ee66-11e8-8271-c48333f09a9b.png">

**Comment by AntonPalich** [comment]
@chihung93 Is there any chance that you enabled `APPLICATION_EXTENSION_API_ONLY` for your pods?

**Comment by AntonPalich** [comment]
@chihung93 This error only appears if you set `APPLICATION_EXTENSION_API_ONLY` ("Requires Only App-Extension-Safe API") to `Yes` for ChattoAdditions target in your pod's project. By default, this setting is set to `No`. That's why Chatto compiles for most projects (including demo app).

**Comment by chihung93** [comment]
@AntonPalich 
I put APPLICATION_EXTENSION_API_ONLY = "No" in my pod, it's work now, but when launching app I got this error.

dyld: Library not loaded: @rpath/Chatto.framework/Chatto
  Referenced from: /Users/me/Library/Developer/Xcode/DerivedData/myapp-bxhrrldpdjcmeyeovfimfunsjpmo/Build/Products/Debug-iphonesimulator/chat.framework/chat
  Reason: image not found

Thank you so much.

**Comment by AntonPalich** [comment]
@chihung93 Do you have App Extension target in your app? If you have it, do you need Chatto in your App Extension? If no, please, configure your Podfile to not include Chatto in App Extension.
