### ISSUE TITLE
Cocoapods & Xcode 10 / swift 4.2 support

### ISSUE THREAD

**Issue by maxkonovalov** [badoo/Chatto#541]
According to #516, swift 4.2 branch is in master, but Cocoapods version is still **3.3.1** - any plans to update the podspecs and push a new tag?

**Comment by dheerajjha** [comment]
for the mean time you can replace your lines

pod 'Chatto', '= 3.3.1'
pod 'ChattoAdditions', '= 3.3.1' # if you want to use the cells or the input component

by

pod 'Chatto', :git => 'https://github.com/badoo/Chatto.git', :branch => 'master'
pod 'ChattoAdditions', :git => 'https://github.com/badoo/Chatto.git', :branch => 'master'


this will take the latest pull from master and no issue will be shown.

**Comment by dheerajjha** [comment]
> According to #516, swift 4.2 branch is in master, but Cocoapods version is still **3.3.1** - any plans to update the podspecs and push a new tag?


for the mean time you can replace your lines

pod 'Chatto', '= 3.3.1'
pod 'ChattoAdditions', '= 3.3.1' # if you want to use the cells or the input component

by

pod 'Chatto', :git => 'https://github.com/badoo/Chatto.git', :branch => 'master'
pod 'ChattoAdditions', :git => 'https://github.com/badoo/Chatto.git', :branch => 'master'

this will take the latest pull from master and no issue will be shown.

**Comment by maxkonovalov** [comment]
@dheerajjha thanks for your suggestion, but, unfortunately, I can't, because I use Chatto as a dependency in my own private podspec, and cocoapods does not allow to specify branches/commits explicitly for pod dependencies.

**Comment by StevenWatremez** [comment]
@maxkonovalov new release `3.4.0` is here. This release is ready for Xcode 10 and Swift 4.2.
