### ISSUE TITLE
Swift 5

### ISSUE THREAD

**Issue by pavelsmelovsky** [badoo/Chatto#564]
Hi there!

Are you planning to upgrade project to Swift 5?

**Comment by PoeticPete** [comment]
It looks like master is upgraded to Swift 5. Use

> pod 'Chatto', :git => 'https://github.com/badoo/Chatto', :branch => 'master'
> pod 'ChattoAdditions', :git => 'https://github.com/badoo/Chatto', :branch => 'master'

in your Podfile for now.

**Comment by pavelsmelovsky** [comment]
@PoeticPete In Podfile and .swift-version files I see version 4.2.
