### ISSUE TITLE
Unused code in Chatto/ChatCollectionViewController.swift

### ISSUE THREAD

**Issue by zwang** [badoo/Chatto#6]
Line 82-88, looks the `oldLayoutModel` is never been used. Is it there for a specific reason? Or this is testing code? Thanks.  

        var oldLayoutModel = self.layoutModel
        self.layoutModel = delegate.chatCollectionViewLayoutModel()
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)) { () -> Void in
            // Dealloc of layout with 5000 items take 25 ms on tests on iPhone 4s
            // This moves dealloc out of main thread
            oldLayoutModel = nil
        }

**Comment by diegosanchezr** [comment]
That's to retain the old model so it's not deallocated on the main thread. If you don't implement a sliding datasource and you load thousands of messages it does make a difference when you paginate.

**Comment by zwang** [comment]
I see. Thank you for the awesome tip. :+1:

**Comment by zwang** [comment]
@diegosanchezr do you think we can get rid of that warning by do a nil check like this:

    if oldLayoutModel != nil {
        oldLayoutModel = nil
    }

I feel it is worth it to get rid of an warning. The performance impact should be minimum given it is done at the background.

**Comment by diegosanchezr** [comment]
Yes, we can do that. Please add a comment explaining that the check is to get rid of the compiler warning. Thanks.

**Comment by zwang** [comment]
Yeah, will do. Thank you.

**Comment by zwang** [comment]
resolved by https://github.com/badoo/Chatto/pull/11
