### ISSUE TITLE
Tutorial baseChat with little mistake

### ISSUE THREAD

**Issue by luckychris** [badoo/Chatto#611]
private func createPhotoInputItem() -> PhotosChatInputItem {
    let item = PhotosChatInputItem(presentingController: self)
    item.photoInputHandler = { [weak self] image in
      // Your handling logic
    }
    return item
}

-> should be

private func createPhotoInputItem() -> PhotosChatInputItem {
    let item = PhotosChatInputItem(presentingController: self)
    item.photoInputHandler = { [weak self] image, imageInputSource in
      // Your handling logic
    }
    return item
}

**Comment by wiruzx** [comment]
Thanks, fixed!
