### ISSUE TITLE
Freeze during TextMessageMenuItemPresenter initialization

### ISSUE THREAD

**Issue by leonspok** [badoo/Chatto#616]
We found that iOS 13 Simulator may freeze when we access UIPasteboard.general. Usually, it happens during TextMessageMenuItemPresenter initialization, which happens when chat screen is initialised. We haven't found this issue to be reproducible on the real device.

<img width="575" alt="Screenshot 2019-09-19 at 11 14 43" src="https://user-images.githubusercontent.com/3374306/66768808-5f778f00-eeab-11e9-960c-525cb739d19c.png">

**Comment by dive** [comment]
It is an issue within Xcode itself, as far as I know. As a workaround, you can disable 'Automatically Sync Pasteboard': Simulator Menu -> Edit -> Automatically Sync Pasteboard -> disable.
It seems that the issue has been fixed with Xcode 11.2 beta.

**Comment by leonspok** [comment]
Then, I guess, there is no need to change anything here
