### ISSUE TITLE
Photo Messages reloading and flickering each time a new message is sent

### ISSUE THREAD

**Issue by rafrybakowski** [badoo/Chatto#618]
Hi, I've been working on a communicator app using Chatto, and I came across an issue with reloading images. If there are some Photo Messages present in the chat, and I send a new message (eg. text, the type makes no difference), all images are getting reloaded. Is this expected behaviour? I noticed that the same thing happens in your ChattoApp example, and it's not very visually appealing. 

Chatto version: 3.5.0
Xcode version: 11.1

**Comment by AntonPalich** [comment]
@rafrybakowski Please, check this: #610
