### ISSUE TITLE
Swift Package Manager?

### ISSUE THREAD

**Issue by leonyannik** [badoo/Chatto#621]
Are there any plans to add this way to install?

**Comment by wiruzx** [comment]
Hey @leonyannik, Thanks for bringing this up.
We're definitely would like to have SPM support, and planning to work on it in the near future!

**Comment by jvigneshcs** [comment]
@NicholasMata, @wiruzx,  Can you please create a new release (tag) with Swift Package Manger Enabled?
I'm getting the following issue with SPM

https://github.com/badoo/Chatto has no Package.swift manifest for version 4.0.0

**Comment by Allow2CEO** [comment]
Linked to #706
