### ISSUE TITLE
Scroll bar insets

### ISSUE THREAD

**Issue by brandtdaniels** [badoo/Chatto#636]
I've created an issue on SO regarding the scroll bar insets I am experiencing in my subclass of BaseChatViewController:

https://stackoverflow.com/questions/59884797/uiscrollview-bar-insets-the-size-of-the-tab-bar-and-nav-bar

Any help here would be preferred.

**Comment by wiruzx** [comment]
Hey @brandtdaniels,
On which iOS version do you see this issue?

**Comment by brandtdaniels** [comment]
iOS 13

**Comment by wiruzx** [comment]
As you've mentioned in your StackOverflow post, I think it's probably related to the navigation and tab bar.
Can you provide some minimal reproducible example so we can help you with that?
Also you can try to override `viewDidLayoutSubviews` and after calling super, call `collectionView.chatto_setVerticalScrollIndicatorInsets` with your own insets

**Comment by brandtdaniels** [comment]
@wiruzx I get this complaint: 
Value of type 'UICollectionView' has no member 'chatto_setVerticalScrollIndicatorInsets'

**Comment by wiruzx** [comment]
@brandtdaniels, Sorry, I missed that it is internal.
Try `collectionView.verticalScrollIndicatorInsets = ` instead

**Comment by brandtdaniels** [comment]
@wiruzx I did confirm that this is not an issue on iOS 12, only seeing it on iOS 13.

This seems to fix the issue:

`
  override func viewDidLayoutSubviews() {

    super.viewDidLayoutSubviews()

    collectionView?.verticalScrollIndicatorInsets = .zero

  }
`
