### ISSUE TITLE
CollectionView didSelectItem not working

### ISSUE THREAD

**Issue by rohitphogat19** [badoo/Chatto#641]
I am trying to implement some logic using 
collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {}

But this function is not firing up. I am not using ChattoAdditions, so Interaction handler protocol is not in scenario

**Comment by wiruzx** [comment]
Hey @rohitphogat19,
Could you please share some details on that? Are you trying to implement this method in a subclass of `BaseChatViewController`?
