### ISSUE TITLE
Swift compiler warnings 3.5.0

### ISSUE THREAD

**Issue by sergeifabian** [badoo/Chatto#647]
Dependency was installed by docs
```
# Swift 5
pod 'Chatto', '= 3.5.0'
pod 'ChattoAdditions', '= 3.5.0' # if you want to use the cells or the input component
```
After `pod install` and `cmd+B` I face multiple swift compiler warnings such as public methods in public extensions. In master it was fixed. How to remove warnings?

**Comment by wiruzx** [comment]
Hey @disquad 
Could you please share more information on those warnings?
Thanks
