### ISSUE TITLE
How to find visible chatItem UIDs?

### ISSUE THREAD

**Issue by Denismih** [badoo/Chatto#649]
Hello. 
I need to save last visible chat item and then scroll to it in next session. Any idea how get UID from self.collectionView?.visibleCells ?

**Comment by wiruzx** [comment]
Hello @Denismih.
You definitely can get `uid` from the `cell.messageViewModel.messageModel`. However that'd require some force-casting and in general not the best practice in my opinion.
I think it'd be better implement `func cellWillBeShown(_ cell: UICollectionViewCell)` of `ChatItemPresenterProtocol` and save this information somewhere
