### ISSUE TITLE
getting "message" with certain uid

### ISSUE THREAD

**Issue by ismailozenc** [badoo/Chatto#66]
first of all thank you for this great framework. 

I would like to know if it is possible to get an outgoing message so that i can modify its status and update it.

like;
message.status = .Success
updateMessage(message)

or is there another way to do this?

thank you for your time in advance

**Comment by diegosanchezr** [comment]
Hi @ismailozenc, you should probably keep track of your messages in your data source; update them and notify Chatto about changes in your data source.

You can also find a message in BaseChatViewController.chatItemCompanionCollection (dev branch) or in the presenter where the message is passed to.

**Comment by ismailozenc** [comment]
I would like to have more clues about how to keep track of my messages in my database if possible. your framework is quite complicated and I am currently unsuccessful to find my way around. thank you.

**Comment by wiruzx** [comment]
Closing as it's probably outdated. Please feel free to reopen if it's still relevant.
