### ISSUE TITLE
3.6.0 seems to have breaking changes to an interface

### ISSUE THREAD

**Issue by brandtdaniels** [badoo/Chatto#663]
super.init(colors: chatColors) 

gives me error message: Must call a designated initializer of the superclass 'BaseMessageCollectionViewCellDefaultStyle'

    super.init(colors: chatColors, bubbleBorderImages: nil, failedIconImages: <#T##BaseMessageCollectionViewCellDefaultStyle.FailedIconImages#>, layoutConstants: <#T##BaseMessageCollectionViewCellLayoutConstants#>, dateTextStyle: <#T##BaseMessageCollectionViewCellDefaultStyle.DateTextStyle#>, avatarStyle: <#T##BaseMessageCollectionViewCellDefaultStyle.AvatarStyle#>, selectionIndicatorStyle: <#T##BaseMessageCollectionViewCellDefaultStyle.SelectionIndicatorStyle#>)

**Comment by wiruzx** [comment]
Hey @brandtdaniels,

Thank you for submitting the issue. It seems like this initializer clashes with convenience init.

It's definitely needs fixing, so I'll put it on our roadmap. 
But as a temporary workaround you can provide default values from `BaseMessageCollectionViewCellDefaultStyle.swift`

Hope that helps,

Thanks!

**Comment by wiruzx** [comment]
Fixed in [this commit](https://github.com/badoo/Chatto/pull/672/commits/1b9dd9ffda0bcb5e46c7a8c964ae1caeda676e40)
