### ISSUE TITLE
How to manage corner radius of BubbleView 

### ISSUE THREAD

**Issue by sundaleek** [badoo/Chatto#664]
Hello
I know BubbleView corners are managed via mask images, but I can not figure out how to create my own image resource for a specific corner radius of BubbleView. 
Any suggestions?

Thanks

**Comment by wiruzx** [comment]
Hey @sundaleek,
Currently we only support this by changing the image resource itself unfortunately.

But if you'd like to contribute to make it more flexible, please let me know, I'll provide you assistance on that.

Thanks
