### ISSUE TITLE
Auto Read OTP is not working

### ISSUE THREAD

**Issue by arjunnna** [badoo/Chatto#669]
Dear Team ,

Auto Read OTP is not working . 

Please enable auto read OTP in the SDK

**Comment by wiruzx** [comment]
Hey @arjunnna,
I assume you're talking about `.oneTimeCode` text content type.

I think it might not be desirable for all users to have this content type, but you can override `createChatInputView` method in your subclass of `BaseChatViewController` and change content type of textView inside of `ChatInputBar`.

I hope that helps.

**Comment by arjunnna** [comment]
Hey @wiruzx 

Thanks for the response . I have override the  createChatInputView in my class which is a subclass of BaseChatViewController and I have changed the content type of the text view also but still OTP auto read is not working .

I have did like below 

I have created a reference to ChatInputBar
**chatInputView = ChatInputBar.loadNib()**

and I have set the content type of textview to  .oneTimeCode

**chatInputView.textView.textContentType = .oneTimeCode**

but still it is not working. 

It will be helpful if you create one branch for OTP auto read .

Regards,
Mallikarjuna C.
