### ISSUE TITLE
How can I use asynchronous image

### ISSUE THREAD

**Issue by mrchenhao** [badoo/Chatto#68]
```
PhotoMessageModel(messageModel: baseMessageModel, imageSize: CGSize.zero, image: ?)
```
I use Kingfisher to download image, how can i use the asynchronous image as UIImage parameter

**Comment by diegosanchezr** [comment]
Hi @mrchenhao,

You have two options.

a. Create a PhotoMessageViewModel subclass as in ChattoApp (DemoPhotoMessageViewModel)
b. Create your own PhotoMessagePresenter and add there the photo downloader

**Comment by mrchenhao** [comment]
I edit the PhotoMessageModelProtocol and use closure to pass the UIimageView out.

```
public protocol PhotoMessageModelProtocol: DecoratedMessageModelProtocol {
//    var image: UIImage { get }
    var imageSize: CGSize { get }
    var imageClosure: PhotoClosure { get }
}

public typealias PhotoClosure =  (imageview: UIImageView) -> ()
```

**Comment by zj2050** [comment]
@mrchenhao hi, would you pls tell how to set and get image from network

**Comment by x-hovo-x** [comment]
Guys, I have also same problem, not clear how to get photo from network, as in PhotoMessageViewModel no url exist to replace fakeImage
