### ISSUE TITLE
Photo image not showing 

### ISSUE THREAD

**Issue by antondityativ** [badoo/Chatto#687]
I'm using this code to display image in cell. But image not showing:
<img width="993" alt="Снимок экрана 2020-10-21 в 17 26 04" src="https://user-images.githubusercontent.com/10920896/96713529-9176d780-13c2-11eb-8938-64eb5ecf0669.png">

**Comment by antondityativ** [comment]
@phatmann @esilverberg @dive @asifmujteba Could you help me?

**Comment by emtjoshhart** [comment]
Same here, just started happening in IOS 14

**Comment by esilverberg** [comment]
Can you guys confirm you are on the latest Chatto?

If not, take a look at this commit: https://github.com/badoo/Chatto/commit/b3840d17a32abf113fdf3448174db3e429c3bb2e

See if you can apply it to your respective branches.

**Comment by emtjoshhart** [comment]
Just confirmed it was from the mask on the image view layer within the PhotoBubbleView.  We had to manually install the framework.  For future devs:

Add these extensions:  https://raw.githubusercontent.com/badoo/Chatto/be313843ab4f222840f60445b2406e638b477b0a/ChattoAdditions/Source/Common/CALayer%2BImageMask.swift

Update Line 179 in PhotoBubbleView.swift to use the new mask:
https://raw.githubusercontent.com/badoo/Chatto/master/ChattoAdditions/Source/Chat%20Items/PhotoMessages/Views/PhotoBubbleView.swift
