### ISSUE TITLE
Very long text is not rendered  (tested with text of 14,8k characters)

### ISSUE THREAD

**Issue by weyg** [badoo/Chatto#70]
See attached screenshot:
![simulator screen shot 22 mar 2016 14 07 55](https://cloud.githubusercontent.com/assets/17618292/13949682/8cc0c3a8-f037-11e5-9128-bf57bf4a03fb.png)

To reproduce add to `TutorialMessageFactory` static messages a couple `("text", "<text from attached file>")`.
[longstring.txt](https://github.com/badoo/Chatto/files/183956/longstring.txt)

File contains 14810 characters and 2081 words.

**Comment by weyg** [comment]
But if I rotate the device to landscape - text appears; and when I rotate the device back to portrait orientation - text disappears!

**Comment by diegosanchezr** [comment]
Happens as well on landscape with the given text doubled. Looks like UITextView is sized correctly.

**Comment by diegosanchezr** [comment]
@weyg it actually renders on real devices

**Comment by weyg** [comment]
> @weyg it actually renders on real devices

Closing an issue then.

@diegosanchezr Thank you for feedback!
