### ISSUE TITLE
Chatto has no Package.swift manifest for version 4.0.0

### ISSUE THREAD

**Issue by Allow2CEO** [badoo/Chatto#706]
a few people also commented on this in #621:

@NicholasMata, @wiruzx, Can you please create a new release (tag) with Swift Package Manger Enabled?
I'm getting the following issue with SPM

https://github.com/badoo/Chatto has no Package.swift manifest for version 4.0.0

**Comment by wiruzx** [comment]
@Allow2CEO you should be able to use `4.1.0`

**Comment by NairaManukyan** [comment]
[!] CocoaPods could not find compatible versions for pod "ChattoAdditions":
  In Podfile:
    ChattoAdditions (= 4.1.0)

None of your spec sources contain a spec satisfying the dependency: `ChattoAdditions (= 4.1.0)`.
