### ISSUE TITLE
Issues migrating integration from Cocoapods to Swift Package

### ISSUE THREAD

**Issue by brandtdaniels** [badoo/Chatto#718]
When attempting to migrate from Cocoapods to Swift Package using 4.1.0

I have several issues where `import ChattoAdditions` is no longer working. Simply updating that import to `import Chatto` is causing other issues. 

Please update your readme.md with clear directions on how to integrate using SPM and how to transition from using ChattoAdditions.

**Comment by maxkonovalov** [comment]
@brandtdaniels I found a solution here - https://forums.swift.org/t/unable-to-import-multiple-targets-from-external-dependency/39030

It works like this:
```
dependencies: [
    .product(name: "Chatto", package: "Chatto"),
    .product(name: "ChattoAdditions", package: "Chatto"),
]
```

**Comment by gsherofly007** [comment]
您好，邮件收到
