### ISSUE TITLE
Question: how to add bunch of messages at the top of dataSource

### ISSUE THREAD

**Issue by weyg** [badoo/Chatto#76]
I'm experimenting with Chatto and looking for a correct way to add a bunch of new messages to top of the data source.

I've tried this one (see my [repo.](https://github.com/weyg/Chatto)):
```swift
    func prependRandomIncomingMessage(count: Int) {
        for _ in 0...count {
            let message = FakeMessageFactory.createChatItem("\(self.nextMessageId)", isIncoming: true)
            self.nextMessageId += 1
            self.slidingWindow.insertItem(message, position: .Top)
        }
        self.delegate?.chatDataSourceDidUpdate(self, context: ChatViewController.UpdateContext.Pagination)
    }
```

e.g. providing context: `.Pagination` and `.Reload` have minor flickering in messages (surely caused by `collectionView.reloadData()`). 

when I use `context: .Pagination` there is no flickering but messages are moving down and up when I do my prepend.

I guess, that I'm doing it wrong. 

Can you help me?

**Comment by diegosanchezr** [comment]
I don't see the messages moving up and down. Are you doing something else apart from prepending? Are you hitting the slidingWindow limit? Normal pagination should work fine as in ChattoApp. Mixing inserts at the top and bottom at the same time or shifting the slidingWindow may have some of these glitches (adjustNumberOfMessages was introduced to separate insertion at the bottom and deletion from  the top in the same update for that reason) . Also please use dev branch; it's got some quite a few changes already and it's easier for us to look for issues in there.

That said, your code looks correct :p

**Comment by weyg** [comment]
> I don't see the messages moving up and down. 

On dev branch, I can't see it too:)

> Are you doing something else apart from prepending? 

No.

> Are you hitting the slidingWindow limit?

I guess, not. 

I've cloned dev branch: [my-dev](https://github.com/weyg/chatto-dev). And you can see the issue with messages moving down/up:
- just enter some chat, 
- wait 5-10 sec, 
- scroll visibleRect away from bottom (and not to the top)
- You'll see that messages are twitching..

Though I'm using `UpdateType.Normal` in `self.delegate?.chatDataSourceDidUpdate(...)`.

If I use `UpdateType.Pagination` theres is a little flicker (for messages containing links) every time new messages are prepended. (Though link flicker may be caused by turning on/off link detection in TextViews).

> Normal pagination should work fine as in ChattoApp.

Does normal pagination change the DataSource?

**Comment by weyg** [comment]
> If I use UpdateType.Pagination theres is a little flicker (for messages containing links) every time new messages are prepended. (Though link flicker may be caused by turning on/off link detection in TextViews).

I've tried to turn off changing  `self.textView.dataDetectorTypes = .None` while `.Sizing`, and there is no flickering..

**Comment by diegosanchezr** [comment]
I see it now. Looks like for performBatchUpdates scrollToPreservePosition should be done inside the batch block ( but we won't compute the proper offset as it is now because the layout hasn't been updated yet ) or use targetContentOffsetForProposedContentOffset(_:) in the UICollectionViewLayout.

The flickering with UITextView and the link detection is something I've seen even with fast scrolling on an iPhone 4s so not sure if something can be done.

I don't have much time to investigate this so contributions are very welcomed :)

**Comment by weyg** [comment]
Assuming that correct usage is to notify the delegate with `context: .Pagination`. And to avoid flickering, for my purposes, I will preserve Link/Phone/etc Detection while Sizing.

**Comment by weyg** [comment]
@diegosanchezr Thank you so much for valuable feedback!
