### ISSUE TITLE
Can I clear the dataSource?

### ISSUE THREAD

**Issue by weyg** [badoo/Chatto#80]
In our chat app user can clear his messaging history. So I've added to `SlidingDataSource` this kind of clear method:
```swift
    public func clear() {
        self.windowCount = 0
        self.windowOffset = 0
        self.itemsOffset = 0
        self.items.removeAll()
    }
```

And I'm using it this way:
```swift
    func clear() {
        self.slidingWindow.clear()
        self.delegate?.chatDataSourceDidUpdate(self, updateType: .Reload)
    }
```

Seems that its not braking anything. Is it correct? If yes, do we need it in master?

**Comment by diegosanchezr** [comment]
Looks fine to me. The SlidingDataSource is not part of the framework and it's just there for demo purposes, so I don't really mind; but if you're adding that functionality then you should also add an option to clear the chat in ChattoApp (and some new tests in SlidingDataSourceTests)

**Comment by diegosanchezr** [comment]
I'm closing this, let us know if you have more questions about this
