### ISSUE TITLE
fatal error when trying to use Chatto in ObjC project

### ISSUE THREAD

**Issue by aytunch** [badoo/Chatto#83]
Hello,
I really want to use Chatto in my nearly finished project which is written in Objective C. I followed instructions and made my XCode project hybrid and I am able to import swift libraries. Since it is not possible to subclass a swift class in objc, i created a swift UIViewController class and inside there subclassed ChatViewController just like in the Chatto example project(DemoChatViewController.swift). Also I am instantiating this class through stroyboard instantiating and viewDidLoad does not run. Later on i did it in code by [[DemoChatViewController alloc] init] but this time class runs as expected. However i get a runtime exception stating:
**"fatal error: unexpectedly found nil while unwrapping an Optional value"**
on the line:
**return BaseMessageHandler(messageSender: self.messageSender)**
Is it not possible to use Chatto in an ObjC project? or am I doing something wrong? Please help needed

**Comment by diegosanchezr** [comment]
That means that messageSender is nil when trying to create BaseMessageHandler. Take a look how the view controller is initialized in ChattoApp
```swift
[...]
chatController.dataSource = dataSource
chatController.messageSender = dataSource.messageSender
```
But you probably want to delete that property and use your own message handler / sender

**Comment by aytunch** [comment]
@diegosanchezr thanks for pointing me to the right direction. I managed to make Chatto work in my ObjC project.
I only needed to make some small adjustments to DemoChatViewController. Maybe somebody might need it so the change is as follows:
    ```

    var messageSender: FakeMessageSender!
    var dataSource: FakeDataSource
    
    lazy private var baseMessageHandler: BaseMessageHandler = {
        return BaseMessageHandler(messageSender: self.messageSender)
    }()
    
    required init?(coder aDecoder: NSCoder) {
        //dataSource = FakeDataSource(count: 0, pageSize: 0)
        dataSource = FakeDataSource(messages: TutorialMessageFactory.createMessages().map { $0 }, pageSize: 50)
        messageSender = dataSource.messageSender
        super.init(coder: aDecoder)
    }
    override func viewDidLoad() {
        super.viewDidLoad()
        self.chatDataSource = self.dataSource
        ...

```

**Comment by keisei1092** [comment]
Hi, I faced same problem and solved with code above. thanks 😀 👍
