### ISSUE TITLE
Enhancement: Isn't it better to use PresenterFactory instead of PresenterBuilders?

### ISSUE THREAD

**Issue by weyg** [badoo/Chatto#87]
We could greatly increase flexibility (and efficiency) of the engine using 
```swift
public protocol ChatItemPresenterFactoryProtocol {
   func createChatItemPresenter(chatItem: ChatItemProtocol?) -> ChatItemPresenterProtocol
}
```
Instead of `ChatItemPresenterBuilders`.

With little effort current `PresenterBuilers` stuff could be placed inside of default factory and be brought out of the Core.

**Note**: We will require `createChatItemPresenter` to produce some `Presenter` even if `nil` is given (we need it where the `DummyPresenter` is used).

I came to this when I tried to change default `DummyPresenter` class to my own:
```swift
    func presenterForIndex(index: Int, chatItemCompanionCollection items: ChatItemCompanionCollection) -> ChatItemPresenterProtocol {
        guard index < items.count else {
            // This can happen from didEndDisplayingCell if we reloaded with less messages
            return DummyChatItemPresenter()  // <-- fixed class (Can I have another class here?)
        }
        return items[index].presenter
    }

```

And saw this:
```swift
    public func createPresenterForChatItem(chatItem: ChatItemProtocol) -> ChatItemPresenterProtocol {
        for builder in self.presenterBuildersByType[chatItem.type] ?? [] {
            if builder.canHandleChatItem(chatItem) { // <-- Isn't it slow? and called many times..
                return builder.createPresenterWithChatItem(chatItem)
            }
        }
        return DummyChatItemPresenter()
    }
```
which may be very slow if there are many presenters created at once and there are lot of chatItemPresenterBuilders registered.

**Comment by weyg** [comment]
Please look at the [diff](https://github.com/weyg/chatto-dev/commit/e21644c0ddebde2d55adf95592f99e573388dc7c). Its not even affecting anything, but gives little more flexibility.

If let it go little further api could become more rewarding..

**Comment by diegosanchezr** [comment]
Hi @weyg,

DummyChatItemPresenter is just there to avoid crashes in case of bugs in Chatto or client code. Can you explain why registering "YourUnsupportedChatItemPresenter" for "your-unsupported-chat-item-type" doesn't work for you?

About the performance, the idea is that you have one presenter builder per `ChatItemType` so the right one is found at the first attempt.

**Comment by weyg** [comment]
I have following logic in my factory:
```
if !myChatItem.isDeleted() { // no matter what the type is
   // select presenter based on 'type'
} else {
   if myChatItem.type == 'Type1' {
      // special presenter
   } else {
     // select Dummy presenter (simplest one, with one label)
   }
}
```
Seems that I misunderstood the purpose of Dummy. With chat builders I'm forced to move this decision making outside of the factory.

**Comment by diegosanchezr** [comment]
Ok, let's do it; but let's keep the DummyChatItemPresenter and let's remove the optional in createChatItemPresenter. See my comments in https://github.com/badoo/Chatto/pull/88

**Comment by weyg** [comment]
Thank you for you comments and feedback. It all makes sense. I admire your work!

Btw I'm not insisting on this issue, just wanted to discuss.. And the easiest way to describe my vision was to make a PR. So its ok if you decide not to take it in:)

**Comment by diegosanchezr** [comment]
@weyg I just wanted to understand how the change was making things better for you. I see that you could still use a "deleted" `ChatItemType` but I can also imagine some disadvantages of that (like duplicated checks for isDeleted depending on how you model your chat items or inconveniences if you rely on `ChatItemType` for something else). I agree that this factory makes all sense so I'm merging https://github.com/badoo/Chatto/pull/89. Thank you!

**Comment by weyg** [comment]
Cool! Thank you again:)
