### ISSUE TITLE
keyboardTracker is nil on ChatViewController using dependency injection

### ISSUE THREAD

**Issue by think-dev** [badoo/Chatto#95]
I am experiencing a major problem when implementing Chatto using a dependency injection pattern (to be concrete, I use the Swinject library).

I'm talking about ChatViewController. It appears that certain variables that need to be initialized before viewWillAppear() method are not exposed, so they cannot be initialized after injection and cause a nullability error.

This happens with `keyboardTracker` specifically.

Is this possible? I'm doing something wrong? I solved the problem temporarily dirty and locally, exposing the following code on ChatViewController:

```
public func performAfterInjection() {
        addCollectionView()
        addInputViews()
        self.keyboardTracker = KeyboardTracker(viewController: self, inputContainer: self.inputContainer, inputContainerBottomContraint: self.inputContainerBottomConstraint, notificationCenter: self.notificationCenter)
    }
```
So when the injection is done I can call this method to init all the stuff that ChatViewController needs to be initialised.

This is just an approach, and all ideas to solve this issue are welcome of course.

**Comment by diegosanchezr** [comment]
Those properties are initialized in `viewDidLoad`. Are you overriding it and not calling the parent implementation?

**Comment by think-dev** [comment]
Yes, I've seen those properties initialized on `viewDidLoad` but I'm not overriding it. 
Your comment has given me a different point of view, and I managed to fix the problem without change `ChatViewController`.

What I've done is to inject the required elements once the injection is done, and force a viewDidLoad() call this way on the proper assembly

```
container.register(TalkingViewController.self) { resolver in
            let chatViewController = TalkingViewController()
            return chatViewController
            }
            .initCompleted { resolver, chatViewController in
                chatViewController.presenter = resolver.resolve(TalkingPresenter)!
                chatViewController.view = resolver.resolve(TalkingView)!
                chatViewController.messageSender = MessageSender()
                chatViewController.baseMessageHandler = BaseMessageHandler(messageSender: chatViewController.messageSender)
                chatViewController.viewDidLoad()
            }
            .inObjectScope(.Container)
```
It works better than the first approach, but feels like it's not very orthodox to force a viewDidLoad() call this way on a dependency injection pattern.

What do you think?

**Comment by diegosanchezr** [comment]
You shouldn't set the view controller's view as you're doing there. That's probably messing up the view controller's lifecycle resulting in viewDidLoad not being called.

**Comment by think-dev** [comment]
Oh god that's it. I was applying the same injection pattern I applied on the application itself and, of course, `ChatViewController` is initialising his own view and not injecting it. I should have guessed it. That was my error. Thank you for your time and support, and sorry for my mistake.
